export type {
    CaseKind,
    FeatureBackend,
    FeatureCase,
    FeatureCaseOptions,
    FeatureCaseRunFail,
    FeatureCaseRunGap,
    FeatureCaseRunOk,
    FeatureCaseRunResult,
    FeatureEffect,
    FeatureEntry,
    FeatureFixtureHooks,
    FeatureHost,
    FeatureMatrix,
    FeatureStatus,
    GapCaseOptions,
    MatrixValidationIssue,
    MatrixValidationResult,
    NegativeCaseOptions,
    PlotCaseOptions,
} from './matrix/index.js';
export {
    assertValidFeatureMatrix,
    entry,
    evalCase,
    FeatureEntryBuilder,
    feature,
    gapCase,
    listRunnableCases,
    matrix,
    negativeCase,
    parseCase,
    plotCase,
    roundtripCase,
    runFeatureCase,
    validateFeatureMatrix,
} from './matrix/index.js';
export { loadDialectFeatureMatrix, reportDialectFeatures } from './report-features.js';
export type { FeatureGapRow } from './reporters/index.js';
export { listGaps, summarizeMatrix, toConsoleRows, toMarkdownTable } from './reporters/index.js';
