export type {
    CaseKind,
    FeatureBackend,
    FeatureBinaryIdentity,
    FeatureCase,
    FeatureCaseFlag,
    FeatureCaseOptions,
    FeatureCaseRunFail,
    FeatureCaseRunGap,
    FeatureCaseRunOk,
    FeatureCaseRunOptions,
    FeatureCaseRunResult,
    FeatureCaseRunWrong,
    FeatureEffect,
    FeatureEntry,
    FeatureFixtureHooks,
    FeatureHost,
    FeatureMatrix,
    FeatureStatus,
    GapCaseOptions,
    IsolatedEvalResult,
    IsolatedEvalSpec,
    MatrixValidationIssue,
    MatrixValidationResult,
    NegativeCaseOptions,
    PlotCaseOptions,
    SuboptimalCaseOptions,
    WellKnownFeatureCaseFlag,
    WrongCaseOptions,
} from './matrix/index.js';
export {
    assertValidFeatureMatrix,
    cosmeticCase,
    entry,
    evalCase,
    FEATURE_CASE_FLAGS,
    FeatureEntryBuilder,
    feature,
    gapCase,
    listRunnableCases,
    matrix,
    mergeCaseFlags,
    negativeCase,
    parseCase,
    plotCase,
    roundtripCase,
    runFeatureCase,
    runIsolatedEval,
    suboptimalCase,
    validateFeatureMatrix,
    wrongCase,
} from './matrix/index.js';
export {
    loadDialectFeatureMatrix,
    reportDialectFeatures,
    resolveDialectFeatureMatrixEntry,
} from './report-features.js';
export type { FeatureFlaggedRow, FeatureGapRow } from './reporters/index.js';
export {
    listCasesByFlags,
    listGaps,
    listSuboptimal,
    listWrongs,
    summarizeMatrix,
    toConsoleRows,
    toMarkdownTable,
} from './reporters/index.js';
