import type { FeatureEntry } from './types.js';

/**
 * MATLAB dialect capability matrix.
 *
 * Status is honest against current SXO + Athena behavior.
 */
export const featureMatrix = [
    {
        name: 'plus',
        category: 'arithmetic',
        status: 'supported',
        effect: 'pure',
        cases: [{ id: 'plus.basic', kind: 'eval', input: '2 + 3', expected: '5' }],
    },
    {
        name: 'mtimes',
        category: 'arithmetic',
        status: 'partial',
        effect: 'pure',
        notes: 'scalar * works; matrix mtimes vs times OperatorId split incomplete',
        cases: [{ id: 'mtimes.scalar', kind: 'eval', input: '2 * 3', expected: '6' }],
    },
    {
        name: 'times',
        category: 'arithmetic',
        status: 'partial',
        effect: 'pure',
        notes: '.* often lowers/renders as * without elementwise OperatorId',
        cases: [
            { id: 'times.scalar', kind: 'eval', input: '2.*[1, 2]', expected: '2*[1, 2]' },
            {
                id: 'times.vec',
                kind: 'gap',
                input: '[1, 2].*[3, 4]',
                expected: '[3, 8]',
                notes: 'needs elementwise Times OperatorId + MatrixValue',
            },
        ],
    },
    {
        name: 'power',
        category: 'arithmetic',
        status: 'supported',
        effect: 'pure',
        cases: [{ id: 'power.basic', kind: 'eval', input: '2^3', expected: '8' }],
    },
    {
        name: 'mrdivide',
        category: 'arithmetic',
        status: 'supported',
        effect: 'pure',
        cases: [{ id: 'mrdivide.basic', kind: 'eval', input: '6 / 2', expected: '3' }],
    },
    {
        name: 'rdivide',
        category: 'arithmetic',
        status: 'partial',
        effect: 'pure',
        cases: [{ id: 'rdivide.scalar', kind: 'eval', input: '1./2', expected: '0.5' }],
    },
    {
        name: 'matrix',
        category: 'matrix',
        status: 'partial',
        effect: 'pure',
        notes: 'literal parse/render works; not yet Athena MatrixValue',
        cases: [
            { id: 'matrix.literal', kind: 'eval', input: '[1, 2; 3, 4]', expected: '[1, 2; 3, 4]' },
            { id: 'matrix.roundtrip', kind: 'roundtrip', input: '[1 2; 3 4]', expected: '[1, 2; 3, 4]' },
        ],
    },
    {
        name: 'colon',
        category: 'indexing',
        status: 'partial',
        effect: 'pure',
        notes: '1:3 becomes Span(1, 3), not expanded range vector',
        cases: [
            {
                id: 'colon.range',
                kind: 'gap',
                input: '1:3',
                expected: '[1, 2, 3]',
                notes: 'must not expand at lowering into flat list without Range/Span object',
            },
        ],
    },
    {
        name: 'subsref',
        category: 'indexing',
        status: 'partial',
        effect: 'pure',
        notes: '1-based vector index works; end/slice/logical incomplete',
        cases: [{ id: 'subsref.vec', kind: 'eval', input: '[1, 2, 3](2)', expected: '2' }],
    },
    {
        name: 'end',
        category: 'indexing',
        status: 'planned',
        effect: 'pure',
        cases: [{ id: 'end.index', kind: 'gap', input: '[1, 2, 3](end)', expected: '3' }],
    },
    {
        name: 'transpose',
        category: 'matrix',
        status: 'planned',
        effect: 'pure',
        cases: [{ id: 'transpose.vec', kind: 'gap', input: "[1; 2]'", expected: '[1, 2]' }],
    },
    {
        name: 'ctranspose',
        category: 'matrix',
        status: 'planned',
        effect: 'pure',
        cases: [{ id: 'ctranspose.basic', kind: 'gap', input: '[1+1i]\'', expected: '1-1i' }],
    },
    {
        name: 'assignment',
        category: 'session',
        status: 'partial',
        effect: 'stateful',
        notes: 'no Session binding persistence',
        cases: [
            {
                id: 'assign.persist',
                kind: 'gap',
                input: 'x = 5; x + 1',
                expected: '6',
                notes: 'currently returns 1 + x',
            },
        ],
    },
    {
        name: 'sequence',
        category: 'session',
        status: 'supported',
        effect: 'pure',
        cases: [{ id: 'seq.last', kind: 'eval', input: '1; 2 + 2', expected: '4' }],
    },
    {
        name: 'if',
        category: 'control',
        status: 'partial',
        effect: 'pure',
        notes: 'surface if/else parses but branch semantics wrong / numeric truthy fragile',
        cases: [
            {
                id: 'if.else',
                kind: 'gap',
                input: 'if 1, 2, else, 3, end',
                expected: '2',
                notes: 'currently returns 3',
            },
        ],
    },
    {
        name: 'for',
        category: 'control',
        status: 'planned',
        effect: 'stateful',
        cases: [{ id: 'for.sum', kind: 'gap', input: 's=0; for i=1:3, s=s+i; end; s', expected: '6' }],
    },
    {
        name: 'function_handle',
        category: 'function',
        status: 'planned',
        effect: 'pure',
        cases: [{ id: 'fh.basic', kind: 'gap', input: 'f=@(x) x^2; f(3)', expected: '9' }],
    },
    {
        name: 'eq',
        category: 'comparison',
        status: 'supported',
        effect: 'pure',
        cases: [{ id: 'eq.true', kind: 'eval', input: '3 == 3', expected: '1' }],
    },
    {
        name: 'ne',
        category: 'comparison',
        status: 'supported',
        effect: 'pure',
        cases: [{ id: 'ne.true', kind: 'eval', input: '3 ~= 2', expected: '1' }],
    },
    {
        name: 'le',
        category: 'comparison',
        status: 'supported',
        effect: 'pure',
        cases: [{ id: 'le.true', kind: 'eval', input: '2 <= 3', expected: '1' }],
    },
    {
        name: 'gt',
        category: 'comparison',
        status: 'supported',
        effect: 'pure',
        cases: [{ id: 'gt.true', kind: 'eval', input: '3 > 2', expected: '1' }],
    },
    {
        name: 'sin',
        category: 'elementary',
        status: 'supported',
        effect: 'pure',
        cases: [{ id: 'sin.0', kind: 'eval', input: 'sin(0)', expected: '0' }],
    },
    {
        name: 'cos',
        category: 'elementary',
        status: 'supported',
        effect: 'pure',
        cases: [{ id: 'cos.0', kind: 'eval', input: 'cos(0)', expected: '1' }],
    },
    {
        name: 'sqrt',
        category: 'elementary',
        status: 'supported',
        effect: 'pure',
        cases: [{ id: 'sqrt.4', kind: 'eval', input: 'sqrt(4)', expected: '2' }],
    },
    {
        name: 'abs',
        category: 'elementary',
        status: 'supported',
        effect: 'pure',
        cases: [{ id: 'abs.neg', kind: 'eval', input: 'abs(-3)', expected: '3' }],
    },
    {
        name: 'simplify',
        category: 'simplify',
        status: 'supported',
        effect: 'pure',
        cases: [
            {
                id: 'simplify.trig',
                kind: 'eval',
                input: 'sin(x)^2 + cos(x)^2',
                expected: '1',
            },
        ],
    },
    {
        name: 'diff',
        category: 'calculus',
        status: 'supported',
        effect: 'pure',
        cases: [
            { id: 'diff.poly', kind: 'eval', input: 'diff(x^3, x)', expected: '3*x^2' },
            { id: 'diff.sin', kind: 'eval', input: 'diff(sin(x), x)', expected: 'cos(x)' },
        ],
    },
    {
        name: 'int',
        category: 'calculus',
        status: 'supported',
        effect: 'pure',
        cases: [{ id: 'int.poly', kind: 'eval', input: 'int(x^2, x)', expected: '1/3*x^3' }],
    },
    {
        name: 'solve',
        category: 'solve',
        status: 'planned',
        effect: 'pure',
        notes: 'must lower to Athena SolveGoal',
        cases: [{ id: 'solve.linear', kind: 'gap', input: 'solve(x-1==0, x)', expected: '1' }],
    },
    {
        name: 'mldivide',
        category: 'solve',
        status: 'planned',
        effect: 'pure',
        cases: [{ id: 'mldivide.2x2', kind: 'gap', input: '[1,2;3,4] \\ [5;6]', expected: '[-4; 4.5]' }],
    },
    {
        name: 'plot',
        category: 'plot',
        status: 'partial',
        effect: 'effectful',
        notes:
            'SVG→PNG visual: curve+L-axes readable; missing tick labels, no boxed frame, not MATLAB default blue. Negative a/b extract fails; 2-arg plot(f,[a,b]) gap',
        cases: [
            {
                id: 'plot.square',
                kind: 'plot',
                input: 'plot(x^2, x, 0, 1)',
                expected: '<svg',
            },
            {
                id: 'plot.sin',
                kind: 'plot',
                input: 'plot(sin(x), x, 0, 6)',
                expected: '<svg',
            },
            {
                id: 'plot.neg_domain',
                kind: 'gap',
                input: 'plot(x^2, x, -1, 1)',
                expected: '<svg',
                notes: 'negative domain bounds fail plot extract',
            },
            {
                id: 'plot.range_vec',
                kind: 'gap',
                input: 'plot(sin(x), [-pi, pi])',
                expected: '<svg',
                notes: 'surface sugar for domain vector',
            },
        ],
    },
    {
        name: 'complex',
        category: 'numeric',
        status: 'planned',
        effect: 'pure',
        cases: [{ id: 'complex.i', kind: 'gap', input: '1+2i', expected: '1+2i' }],
    },
] as const satisfies readonly FeatureEntry[];
