import type { FeatureEntry } from './types.js';

/**
 * MATLAB dialect capability matrix.
 *
 * Status is honest against current SXO + Athena behavior.
 */
export const featureMatrix = [
    {
        name: 'plus',
        category: 'arithmetic',
        status: 'supported',
        effect: 'pure',
        cases: [{ id: 'plus.basic', kind: 'eval', input: '2 + 3', expected: '5' }],
    },
    {
        name: 'mtimes',
        category: 'arithmetic',
        status: 'partial',
        effect: 'pure',
        notes: 'scalar * and numeric nested-list matmul work; symbolic matrix * stays Times',
        cases: [
            { id: 'mtimes.scalar', kind: 'eval', input: '2 * 3', expected: '6' },
            {
                id: 'mtimes.2x2',
                kind: 'gap',
                input: '[1, 2; 3, 4]*[5, 6; 7, 8]',
                expected: '[19, 22; 43, 50]',
                notes: 'currently [1, 2; 3, 4]*[5, 6; 7, 8]',
            },
        ],
    },
    {
        name: 'times',
        category: 'arithmetic',
        status: 'supported',
        effect: 'pure',
        notes: '.* → DotTimes elementwise',
        cases: [
            { id: 'times.scalar', kind: 'eval', input: '2 .* [1, 2]', expected: '[2, 4]' },
            { id: 'times.vec', kind: 'eval', input: '[1, 2].*[3, 4]', expected: '[3, 8]' },
        ],
    },
    {
        name: 'power',
        category: 'arithmetic',
        status: 'partial',
        effect: 'pure',
        notes: 'scalar ^ and .^ OK; (x+1)^2 still expands',
        cases: [
            { id: 'power.basic', kind: 'eval', input: '2^3', expected: '8' },
            { id: 'power.elementwise', kind: 'eval', input: '[1, 2].^[2, 3]', expected: '[1, 8]' },
            {
                id: 'power.binomsq',
                kind: 'gap',
                input: '(x + 1)^2',
                expected: '(x + 1)^2',
                notes: 'currently expands',
            },
            { id: 'power.vec_pow0', kind: 'eval', input: '[1, 2, 3].^0', expected: '[1, 1, 1]' },
        ],
    },
    {
        name: 'mrdivide',
        category: 'arithmetic',
        status: 'supported',
        effect: 'pure',
        cases: [{ id: 'mrdivide.basic', kind: 'eval', input: '6 / 2', expected: '3' }],
    },
    {
        name: 'rdivide',
        category: 'arithmetic',
        status: 'supported',
        effect: 'pure',
        notes: './ → DotDivide',
        cases: [
            { id: 'rdivide.scalar', kind: 'eval', input: '1./2', expected: '0.5' },
            { id: 'rdivide.vec', kind: 'eval', input: '[6, 8]./[2, 4]', expected: '[3, 2]' },
        ],
    },
    {
        name: 'matrix',
        category: 'matrix',
        status: 'partial',
        effect: 'pure',
        notes: 'literal nested List + constructors via MatrixValue bridge; MatrixId IR pending',
        cases: [
            { id: 'matrix.literal', kind: 'eval', input: '[1, 2; 3, 4]', expected: '[1, 2; 3, 4]' },
            { id: 'matrix.roundtrip', kind: 'roundtrip', input: '[1 2; 3 4]', expected: '[1, 2; 3, 4]' },
        ],
    },
    {
        name: 'colon',
        category: 'indexing',
        status: 'supported',
        effect: 'pure',
        notes: '1:n and a:step:b expand to numeric row vectors',
        cases: [
            { id: 'colon.range', kind: 'eval', input: '1:3', expected: '[1, 2, 3]' },
            { id: 'colon.step', kind: 'eval', input: '1:2:10', expected: '[1, 3, 5, 7, 9]' },
        ],
    },
    {
        name: 'subsref',
        category: 'indexing',
        status: 'supported',
        effect: 'pure',
        cases: [
            { id: 'subsref.vec', kind: 'eval', input: '[1, 2, 3](2)', expected: '2' },
            { id: 'subsref.matrix', kind: 'eval', input: '[1, 2; 3, 4](1, 2)', expected: '2' },
            { id: 'subsref.slice', kind: 'eval', input: '[1, 2, 3](1:2)', expected: '[1, 2]' },
        ],
    },
    {
        name: 'end',
        category: 'indexing',
        status: 'supported',
        effect: 'pure',
        cases: [{ id: 'end.index', kind: 'eval', input: '[1, 2, 3](end)', expected: '3' }],
    },
    {
        name: 'transpose',
        category: 'matrix',
        status: 'unsupported',
        effect: 'pure',
        notes: "oak rejects ' transpose literal",
        cases: [{ id: 'transpose.vec', kind: 'gap', input: "[1; 2]'", expected: '[1, 2]' }],
    },
    {
        name: 'ctranspose',
        category: 'matrix',
        status: 'unsupported',
        effect: 'pure',
        notes: "depends on complex literal + '",
        cases: [{ id: 'ctranspose.basic', kind: 'gap', input: "[1+1i]'", expected: '1-1i' }],
    },
    {
        name: 'assignment',
        category: 'session',
        status: 'supported',
        effect: 'stateful',
        notes: 'compound assignment binds in one evaluate string',
        cases: [
            { id: 'assign.compound', kind: 'eval', input: 'x = 5; x + 1', expected: '6' },
            {
                id: 'assign.persist',
                kind: 'eval',
                input: 'x = 5',
                expected: '5',
                notes: 'follow-up x+1 on same Session → 6 (napi session test)',
            },
        ],
    },
    {
        name: 'sequence',
        category: 'session',
        status: 'supported',
        effect: 'pure',
        cases: [{ id: 'seq.last', kind: 'eval', input: '1; 2 + 2', expected: '4' }],
    },
    {
        name: 'if',
        category: 'control',
        status: 'supported',
        effect: 'pure',
        cases: [{ id: 'if.else', kind: 'eval', input: 'if 1, 2, else, 3, end', expected: '2' }],
    },
    {
        name: 'for',
        category: 'control',
        status: 'supported',
        effect: 'stateful',
        notes: 'for i=1:n last value and compound accumulator via shared Session bindings',
        cases: [
            { id: 'for.last', kind: 'eval', input: 'for i=1:3, i, end', expected: '3' },
            {
                id: 'for.sum',
                kind: 'eval',
                input: 's=0; for i=1:3, s=s+i; end; s',
                expected: '6',
            },
        ],
    },
    {
        name: 'while',
        category: 'control',
        status: 'supported',
        effect: 'stateful',
        notes: 'while 0 skips body; empty result renders as []',
        cases: [{ id: 'while.false', kind: 'eval', input: 'while 0, 1, end', expected: '[]' }],
    },
    {
        name: 'function_handle',
        category: 'function',
        status: 'unsupported',
        effect: 'pure',
        notes: 'oak error on @(x); feval(@sin,0) strips @',
        cases: [
            { id: 'fh.basic', kind: 'gap', input: 'f=@(x)x^2; f(4)', expected: '16' },
            {
                id: 'fh.feval',
                kind: 'gap',
                input: 'feval(@sin, 0)',
                expected: '0',
                notes: 'currently feval(sin, 0)',
            },
        ],
    },
    {
        name: 'eq',
        category: 'comparison',
        status: 'supported',
        effect: 'pure',
        cases: [{ id: 'eq.true', kind: 'eval', input: '3 == 3', expected: 'true' }],
    },
    {
        name: 'ne',
        category: 'comparison',
        status: 'partial',
        effect: 'pure',
        notes: 'scalar ~= OK; vector [1,2]~=[1,3] stays Unequal head not elementwise mask',
        cases: [
            { id: 'ne.true', kind: 'eval', input: '3 ~= 2', expected: 'true' },
            { id: 'ne.false', kind: 'eval', input: '1 ~= 1', expected: 'false' },
            {
                id: 'ne.vec',
                kind: 'gap',
                input: '[1, 2] ~= [1, 3]',
                expected: '[0, 1]',
                notes: 'currently Unequal([1, 2], [1, 3])',
            },
        ],
    },
    {
        name: 'le',
        category: 'comparison',
        status: 'partial',
        effect: 'pure',
        notes: 'scalar <= OK; vector / functional le(…) unevaluated',
        cases: [
            { id: 'le.true', kind: 'eval', input: '2 <= 3', expected: 'true' },
            {
                id: 'le.vec',
                kind: 'gap',
                input: '[1, 2] <= [1, 3]',
                expected: '[1, 1]',
            },
            {
                id: 'le.fn',
                kind: 'gap',
                input: 'le(1, 2)',
                expected: 'true',
            },
        ],
    },
    {
        name: 'ge',
        category: 'comparison',
        status: 'partial',
        effect: 'pure',
        notes: 'scalar >= OK; vector / functional ge(…) unevaluated',
        cases: [
            { id: 'ge.true', kind: 'eval', input: '1 >= 1', expected: 'true' },
            { id: 'ge.false', kind: 'eval', input: '1 >= 2', expected: 'false' },
            {
                id: 'ge.vec',
                kind: 'gap',
                input: '[1, 2, 3] >= 2',
                expected: '[0, 1, 1]',
            },
            {
                id: 'ge.fn',
                kind: 'gap',
                input: 'ge(2, 2)',
                expected: 'true',
            },
        ],
    },
    {
        name: 'gt',
        category: 'comparison',
        status: 'supported',
        effect: 'pure',
        cases: [{ id: 'gt.true', kind: 'eval', input: '3 > 2', expected: 'true' }],
    },
    {
        name: 'sin',
        category: 'elementary',
        status: 'supported',
        effect: 'pure',
        cases: [{ id: 'sin.0', kind: 'eval', input: 'sin(0)', expected: '0' }],
    },
    {
        name: 'cos',
        category: 'elementary',
        status: 'supported',
        effect: 'pure',
        cases: [{ id: 'cos.0', kind: 'eval', input: 'cos(0)', expected: '1' }],
    },
    {
        name: 'sqrt',
        category: 'elementary',
        status: 'supported',
        effect: 'pure',
        cases: [{ id: 'sqrt.4', kind: 'eval', input: 'sqrt(4)', expected: '2' }],
    },
    {
        name: 'abs',
        category: 'elementary',
        status: 'supported',
        effect: 'pure',
        cases: [{ id: 'abs.neg', kind: 'eval', input: 'abs(-3)', expected: '3' }],
    },
    {
        name: 'exp',
        category: 'elementary',
        status: 'supported',
        effect: 'pure',
        cases: [{ id: 'exp.0', kind: 'eval', input: 'exp(0)', expected: '1' }],
    },
    {
        name: 'log',
        category: 'elementary',
        status: 'supported',
        effect: 'pure',
        cases: [{ id: 'log.1', kind: 'eval', input: 'log(1)', expected: '0' }],
    },
    {
        name: 'listable_sin',
        category: 'elementary',
        status: 'unsupported',
        effect: 'pure',
        notes: 'sin on vector left as sin([...])',
        cases: [
            {
                id: 'sin.listable',
                kind: 'gap',
                input: 'sin([0, pi/2])',
                expected: '[0, 1]',
            },
        ],
    },
    {
        name: 'simplify',
        category: 'simplify',
        status: 'supported',
        effect: 'pure',
        cases: [
            {
                id: 'simplify.trig',
                kind: 'eval',
                input: 'sin(x)^2 + cos(x)^2',
                expected: '1',
            },
        ],
    },
    {
        name: 'diff',
        category: 'calculus',
        status: 'partial',
        effect: 'pure',
        notes: 'first derivative works; higher-order diff(f,x,2) unevaluated',
        cases: [
            { id: 'diff.poly', kind: 'eval', input: 'diff(x^3, x)', expected: '3*x^2' },
            { id: 'diff.sin', kind: 'eval', input: 'diff(sin(x), x)', expected: 'cos(x)' },
            {
                id: 'diff.order2',
                kind: 'gap',
                input: 'diff(x^2, x, 2)',
                expected: '2',
            },
        ],
    },
    {
        name: 'int',
        category: 'calculus',
        status: 'supported',
        effect: 'pure',
        cases: [
            { id: 'int.poly', kind: 'eval', input: 'int(x^2, x)', expected: '1/3*x^3' },
            { id: 'int.sin', kind: 'eval', input: 'int(sin(x), x)', expected: '-cos(x)' },
        ],
    },
    {
        name: 'solve',
        category: 'solve',
        status: 'planned',
        effect: 'pure',
        notes: 'must lower to Athena SolveGoal',
        cases: [{ id: 'solve.linear', kind: 'gap', input: 'solve(x-1==0, x)', expected: '1' }],
    },
    {
        name: 'mldivide',
        category: 'solve',
        status: 'supported',
        effect: 'pure',
        notes: 'exact numeric nested-list A\\b; symbolic stays unevaluated',
        cases: [
            {
                id: 'mldivide.2x2',
                kind: 'eval',
                input: '[1,2;3,4] \\ [5;6]',
                expected: '[-4; 9/2]',
            },
        ],
    },
    {
        name: 'linsolve',
        category: 'solve',
        status: 'unsupported',
        effect: 'pure',
        notes: 'linsolve → LinearSolve; same exact bridge as mldivide',
        cases: [
            {
                id: 'linsolve.2x2',
                kind: 'gap',
                input: 'linsolve([1, 2; 3, 4], [5; 6])',
                expected: '[-4; 9/2]',
                notes: 'currently linsolve([1, 2; 3, 4], [5; 6])',
            },
        ],
    },
    {
        name: 'roots',
        category: 'solve',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'roots.quad', kind: 'gap', input: 'roots([1, 0, -1])', expected: '[1; -1]' }],
    },
    {
        name: 'det',
        category: 'linear_algebra',
        status: 'supported',
        effect: 'pure',
        cases: [{ id: 'det.2x2', kind: 'eval', input: 'det([1, 2; 3, 4])', expected: '-2' }],
    },
    {
        name: 'inv',
        category: 'linear_algebra',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'inv.diag', kind: 'gap', input: 'inv([1, 0; 0, 2])', expected: '[1, 0; 0, 0.5]' }],
    },
    {
        name: 'rank',
        category: 'linear_algebra',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'rank.def', kind: 'gap', input: 'rank([1, 2; 2, 4])', expected: '1' }],
    },
    {
        name: 'eig',
        category: 'linear_algebra',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'eig.sym', kind: 'gap', input: 'eig([1, 2; 2, 1])', expected: '[3; -1]' }],
    },
    {
        name: 'eye',
        category: 'matrix',
        status: 'supported',
        effect: 'pure',
        cases: [{ id: 'eye.2', kind: 'eval', input: 'eye(2)', expected: '[1, 0; 0, 1]' }],
    },
    {
        name: 'zeros',
        category: 'matrix',
        status: 'supported',
        effect: 'pure',
        cases: [{ id: 'zeros.23', kind: 'eval', input: 'zeros(2, 3)', expected: '[0, 0, 0; 0, 0, 0]' }],
    },
    {
        name: 'ones',
        category: 'matrix',
        status: 'supported',
        effect: 'pure',
        cases: [{ id: 'ones.2', kind: 'eval', input: 'ones(2)', expected: '[1, 1; 1, 1]' }],
    },
    {
        name: 'size',
        category: 'matrix',
        status: 'supported',
        effect: 'pure',
        cases: [{ id: 'size.2x2', kind: 'eval', input: 'size([1, 2; 3, 4])', expected: '[2, 2]' }],
    },
    {
        name: 'length',
        category: 'matrix',
        status: 'supported',
        effect: 'pure',
        cases: [{ id: 'length.vec', kind: 'eval', input: 'length([1, 2, 3])', expected: '3' }],
    },
    {
        name: 'sum',
        category: 'matrix',
        status: 'supported',
        effect: 'pure',
        notes: 'vector → scalar; matrix → column sums',
        cases: [
            { id: 'sum.vec', kind: 'eval', input: 'sum([1, 2, 3])', expected: '6' },
            { id: 'sum.matrix', kind: 'eval', input: 'sum([1, 2; 3, 4])', expected: '[4, 6]' },
        ],
    },
    {
        name: 'max',
        category: 'matrix',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'max.vec', kind: 'gap', input: 'max([1, 3, 2])', expected: '3' }],
    },
    {
        name: 'plot',
        category: 'plot',
        status: 'partial',
        effect: 'effectful',
        notes:
            'SVG→PNG visual: curve+L-axes readable; missing tick labels, no boxed frame, not MATLAB default blue. Negative a/b via unary-minus fold; 2-arg plot(f,[a,b]) gap',
        cases: [
            {
                id: 'plot.square',
                kind: 'plot',
                input: 'plot(x^2, x, 0, 1)',
                expected: '<svg',
            },
            {
                id: 'plot.sin',
                kind: 'plot',
                input: 'plot(sin(x), x, 0, 6)',
                expected: '<svg',
            },
            {
                id: 'plot.neg_domain',
                kind: 'gap',
                input: 'plot(x^2, x, -1, 1)',
                expected: '<svg',
                notes: 'currently not a supported 1-D plot form',
            },
            {
                id: 'plot.range_vec',
                kind: 'gap',
                input: 'plot(sin(x), [-pi, pi])',
                expected: '<svg',
                notes: 'surface sugar for domain vector',
            },
        ],
    },
    {
        name: 'mesh',
        category: 'plot',
        status: 'unsupported',
        effect: 'effectful',
        cases: [{ id: 'mesh.peaks', kind: 'gap', input: 'mesh(peaks)', expected: '<svg' }],
    },
    {
        name: 'complex',
        category: 'numeric',
        status: 'unsupported',
        effect: 'pure',
        notes: 'oak bad literal on 2i',
        cases: [
            { id: 'complex.i', kind: 'gap', input: '1+2i', expected: '1+2i' },
            { id: 'complex.real', kind: 'gap', input: 'real(1+2i)', expected: '1' },
        ],
    },
    {
        name: 'pi',
        category: 'constant',
        status: 'partial',
        effect: 'pure',
        cases: [{ id: 'pi.symbol', kind: 'eval', input: 'pi', expected: 'pi' }],
    },
    {
        name: 'true',
        category: 'constant',
        status: 'partial',
        effect: 'pure',
        cases: [{ id: 'true.atom', kind: 'eval', input: 'true', expected: 'true' }],
    },
    {
        name: 'false',
        category: 'constant',
        status: 'partial',
        effect: 'pure',
        cases: [{ id: 'false.atom', kind: 'eval', input: 'false', expected: 'false' }],
    },
    {
        name: 'disp',
        category: 'io',
        status: 'unsupported',
        effect: 'effectful',
        cases: [{ id: 'disp.1', kind: 'gap', input: 'disp(1)', expected: '1' }],
    },
    {
        name: 'linspace',
        category: 'matrix',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'linspace.3', kind: 'gap', input: 'linspace(0, 1, 3)', expected: '[0, 0.5, 1]' }],
    },
    {
        name: 'diag',
        category: 'linear_algebra',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'diag.vec', kind: 'gap', input: 'diag([1, 2])', expected: '[1, 0; 0, 2]' }],
    },
    {
        name: 'trace',
        category: 'linear_algebra',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'trace.2x2', kind: 'gap', input: 'trace([1, 2; 3, 4])', expected: '5' }],
    },
    {
        name: 'norm',
        category: 'linear_algebra',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'norm.34', kind: 'gap', input: 'norm([3, 4])', expected: '5' }],
    },
    {
        name: 'dot',
        category: 'linear_algebra',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'dot.2', kind: 'gap', input: 'dot([1, 2], [3, 4])', expected: '11' }],
    },
    {
        name: 'cross',
        category: 'linear_algebra',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'cross.ijk', kind: 'gap', input: 'cross([1, 0, 0], [0, 1, 0])', expected: '[0, 0, 1]' }],
    },
    {
        name: 'reshape',
        category: 'matrix',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'reshape.22', kind: 'gap', input: 'reshape([1, 2, 3, 4], 2, 2)', expected: '[1, 3; 2, 4]' }],
    },
    {
        name: 'sort',
        category: 'matrix',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'sort.vec', kind: 'gap', input: 'sort([3, 1, 2])', expected: '[1, 2, 3]' }],
    },
    {
        name: 'mean',
        category: 'stats',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'mean.vec', kind: 'gap', input: 'mean([1, 2, 3])', expected: '2' }],
    },
    {
        name: 'std',
        category: 'stats',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'std.vec', kind: 'gap', input: 'std([1, 2, 3])', expected: '1' }],
    },
    {
        name: 'fft',
        category: 'signal',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'fft.4', kind: 'gap', input: 'fft([1, 2, 3, 4])', expected: '...' }],
    },
    {
        name: 'polyval',
        category: 'polynomial',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'polyval.quad', kind: 'gap', input: 'polyval([1, 0, -1], 2)', expected: '3' }],
    },
    {
        name: 'elementwise_compare',
        category: 'comparison',
        status: 'unsupported',
        effect: 'pure',
        notes: 'vectorized > / == become Greater/Equal heads, not logical masks',
        cases: [
            {
                id: 'gt.vec',
                kind: 'gap',
                input: '[1, 2, 3] > 2',
                expected: '[0, 0, 1]',
                notes: 'currently Greater([1, 2, 3], 2)',
            },
        ],
    },
    {
        name: 'cell',
        category: 'types',
        status: 'unsupported',
        effect: 'pure',
        notes: 'SILENT WRONG: {1,2} evaluates to 2 (brace not cell)',
        cases: [
            {
                id: 'cell.literal',
                kind: 'gap',
                input: '{1, 2}',
                expected: '{1, 2}',
                notes: 'currently returns 2',
            },
            { id: 'cell.ctor', kind: 'gap', input: 'cell(2, 1)', expected: '{[]; []}' },
        ],
    },
    {
        name: 'struct',
        category: 'types',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'struct.basic', kind: 'gap', input: "struct('a', 1)", expected: "struct('a',1)" }],
    },
    {
        name: 'ode45',
        category: 'ode',
        status: 'unsupported',
        effect: 'pure',
        notes: 'SILENT WRONG: ode45(@(t,y)y,[0,1],1) → 1 (strips to last arg)',
        cases: [
            {
                id: 'ode45.strip',
                kind: 'gap',
                input: 'ode45(@(t,y)y, [0, 1], 1)',
                expected: '...',
                notes: 'currently returns 1',
            },
        ],
    },
    {
        name: 'fzero',
        category: 'solve',
        status: 'unsupported',
        effect: 'pure',
        notes: '@ handle stripped; args mangled to fzero(x, -2+x^2, 1)',
        cases: [{ id: 'fzero.sqrt2', kind: 'gap', input: 'fzero(@(x)x^2-2, 1)', expected: '1.4142' }],
    },
    {
        name: 'integral',
        category: 'calculus',
        status: 'unsupported',
        effect: 'pure',
        notes: '@ stripped to integral(x, sin(x), 0, pi)',
        cases: [{ id: 'integral.sin', kind: 'gap', input: 'integral(@(x)sin(x), 0, pi)', expected: '2' }],
    },
    {
        name: 'switch',
        category: 'control',
        status: 'unsupported',
        effect: 'pure',
        notes: 'SILENT WRONG: switch 1, case 1, 2, otherwise, 3, end → 3',
        cases: [
            {
                id: 'switch.case1',
                kind: 'gap',
                input: 'switch 1, case 1, 2, otherwise, 3, end',
                expected: '2',
                notes: 'currently returns 3',
            },
        ],
    },
    {
        name: 'try_catch',
        category: 'control',
        status: 'supported',
        effect: 'pure',
        notes: 'oak Statement::Try → Athena Try[body, catch]; success and error paths',
        cases: [
            {
                id: 'try.catch',
                kind: 'eval',
                input: "try, error('e'), catch, 1, end",
                expected: '1',
            },
            {
                id: 'try.no_error',
                kind: 'eval',
                input: 'try, 2, catch, 3, end',
                expected: '2',
            },
        ],
    },
    {
        name: 'global',
        category: 'session',
        status: 'unsupported',
        effect: 'stateful',
        notes: 'SILENT WRONG: global x → x',
        cases: [{ id: 'global.strip', kind: 'gap', input: 'global x', expected: '' }],
    },
    {
        name: 'persistent',
        category: 'session',
        status: 'unsupported',
        effect: 'stateful',
        notes: 'SILENT WRONG: persistent y → y',
        cases: [{ id: 'persistent.strip', kind: 'gap', input: 'persistent y', expected: '' }],
    },
    {
        name: 'which',
        category: 'meta',
        status: 'unsupported',
        effect: 'pure',
        notes: 'SILENT WRONG: which sin → sin',
        cases: [{ id: 'which.sin', kind: 'gap', input: 'which sin', expected: '...' }],
    },
    {
        name: 'row_colon',
        category: 'indexing',
        status: 'supported',
        effect: 'pure',
        notes: 'All-colon row/col on literals; column as flat list of picks',
        cases: [
            { id: 'row.colon', kind: 'eval', input: '[1, 2; 3, 4](1,:)', expected: '[1, 2]' },
            { id: 'col.colon', kind: 'eval', input: '[1, 2; 3, 4](:,2)', expected: '[2, 4]' },
        ],
    },
    {
        name: 'logical_index',
        category: 'indexing',
        status: 'unsupported',
        effect: 'pure',
        cases: [
            {
                id: 'logical.gt',
                kind: 'gap',
                input: 'A=[1,2,3]; A(A>1)',
                expected: '[2, 3]',
            },
        ],
    },
    {
        name: 'surf',
        category: 'plot',
        status: 'unsupported',
        effect: 'effectful',
        cases: [{ id: 'surf.peaks', kind: 'gap', input: 'surf(peaks)', expected: '<svg' }],
    },
    {
        name: 'contour',
        category: 'plot',
        status: 'unsupported',
        effect: 'effectful',
        cases: [{ id: 'contour.peaks', kind: 'gap', input: 'contour(peaks)', expected: '<svg' }],
    },
    {
        name: 'figure',
        category: 'plot',
        status: 'unsupported',
        effect: 'effectful',
        cases: [{ id: 'figure.basic', kind: 'gap', input: 'figure', expected: '...' }],
    },
    {
        name: 'sparse',
        category: 'matrix',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'sparse.diag', kind: 'gap', input: 'sparse([1, 0; 0, 2])', expected: '...' }],
    },
    {
        name: 'num2str',
        category: 'string',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'num2str.3', kind: 'gap', input: 'num2str(3)', expected: "'3'" }],
    },
    {
        name: 'str2num',
        category: 'string',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'str2num.3', kind: 'gap', input: "str2num('3')", expected: '3' }],
    },
    // --- wave 4: matrix gallery / ODE / types / IO probes ---
    {
        name: 'pascal',
        category: 'matrix',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'pascal.3', kind: 'gap', input: 'pascal(3)', expected: '[1,1,1; 1,2,3; 1,3,6]' }],
    },
    {
        name: 'magic',
        category: 'matrix',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'magic.3', kind: 'gap', input: 'magic(3)', expected: '...' }],
    },
    {
        name: 'cond',
        category: 'linear_algebra',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'cond.2x2', kind: 'gap', input: 'cond([1, 2; 3, 4])', expected: '...' }],
    },
    {
        name: 'null',
        category: 'linear_algebra',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'null.rank1', kind: 'gap', input: 'null([1, 2; 2, 4])', expected: '...' }],
    },
    {
        name: 'pinv',
        category: 'linear_algebra',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'pinv.2x2', kind: 'gap', input: 'pinv([1, 2; 3, 4])', expected: '...' }],
    },
    {
        name: 'svd',
        category: 'linear_algebra',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'svd.2x2', kind: 'gap', input: 'svd([1, 2; 3, 4])', expected: '...' }],
    },
    {
        name: 'kron',
        category: 'linear_algebra',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'kron.basic', kind: 'gap', input: 'kron([1, 2], [3, 4])', expected: '[3,4,6,8]' }],
    },
    {
        name: 'polyfit',
        category: 'fit',
        status: 'unsupported',
        effect: 'pure',
        cases: [
            {
                id: 'polyfit.quad',
                kind: 'gap',
                input: 'polyfit([1, 2, 3], [1, 4, 9], 2)',
                expected: '[1, 0, 0]',
            },
        ],
    },
    {
        name: 'interp1',
        category: 'fit',
        status: 'unsupported',
        effect: 'pure',
        cases: [
            {
                id: 'interp1.mid',
                kind: 'gap',
                input: 'interp1([0, 1], [0, 1], 0.5)',
                expected: '0.5',
            },
        ],
    },
    {
        name: 'ode23',
        category: 'ode',
        status: 'unsupported',
        effect: 'pure',
        notes: 'SILENT WRONG: ode23(@(t,y)y,[0,1],1) → 1 (same strip pattern as ode45)',
        cases: [
            {
                id: 'ode23.strip',
                kind: 'gap',
                input: 'ode23(@(t,y)y, [0, 1], 1)',
                expected: '...',
                notes: 'currently returns 1',
            },
        ],
    },
    {
        name: 'fsolve',
        category: 'solve',
        status: 'unsupported',
        effect: 'pure',
        notes: '@ handle stripped; args mangled like fzero',
        cases: [
            {
                id: 'fsolve.sqrt2',
                kind: 'gap',
                input: 'fsolve(@(x)x^2-2, 1)',
                expected: '1.4142',
            },
        ],
    },
    {
        name: 'class',
        category: 'types',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'class.double', kind: 'gap', input: 'class(1)', expected: "'double'" }],
    },
    {
        name: 'isa',
        category: 'types',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'isa.double', kind: 'gap', input: "isa(1, 'double')", expected: '1' }],
    },
    {
        name: 'isnumeric',
        category: 'types',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'isnumeric.1', kind: 'gap', input: 'isnumeric(1)', expected: '1' }],
    },
    {
        name: 'assert',
        category: 'control',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'assert.true', kind: 'gap', input: 'assert(1)', expected: '...' }],
    },
    {
        name: 'imag_unit_literal',
        category: 'numeric',
        status: 'unsupported',
        effect: 'pure',
        notes: 'oak bad literal on bare 1i (also 2i in complex entry)',
        cases: [{ id: 'imag.1i', kind: 'gap', input: '1i', expected: '1i' }],
    },
    {
        name: 'complex_ctor',
        category: 'numeric',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'complex.ctor', kind: 'gap', input: 'complex(1, 2)', expected: '1+2i' }],
    },
    {
        name: 'single',
        category: 'numeric',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'single.1', kind: 'gap', input: 'single(1)', expected: '1' }],
    },
    {
        name: 'nan',
        category: 'constant',
        status: 'partial',
        effect: 'pure',
        notes: 'lowercase atom retained; NaN arithmetic / isnan contract incomplete',
        cases: [{ id: 'nan.lower', kind: 'eval', input: 'nan', expected: 'nan' }],
    },
    {
        name: 'eps',
        category: 'constant',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'eps.atom', kind: 'gap', input: 'eps', expected: '...' }],
    },
    {
        name: 'diff_vector',
        category: 'array',
        status: 'unsupported',
        effect: 'pure',
        notes: 'vector difference op distinct from symbolic diff(f,x)',
        cases: [{ id: 'diffvec.3', kind: 'gap', input: 'diff([1, 4, 9])', expected: '[3, 5]' }],
    },
    {
        name: 'cumsum',
        category: 'array',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'cumsum.3', kind: 'gap', input: 'cumsum([1, 2, 3])', expected: '[1, 3, 6]' }],
    },
    {
        name: 'contains',
        category: 'string',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'contains.b', kind: 'gap', input: "contains('abc', 'b')", expected: '1' }],
    },
    {
        name: 'string',
        category: 'string',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'string.ctor', kind: 'gap', input: "string('ab')", expected: '"ab"' }],
    },
    {
        name: 'jsonencode',
        category: 'io',
        status: 'unsupported',
        effect: 'pure',
        cases: [
            {
                id: 'jsonencode.struct',
                kind: 'gap',
                input: "jsonencode(struct('a', 1))",
                expected: '{"a":1}',
            },
        ],
    },
    {
        name: 'datetime',
        category: 'types',
        status: 'unsupported',
        effect: 'pure',
        cases: [
            {
                id: 'datetime.ymd',
                kind: 'gap',
                input: 'datetime(2020, 1, 1)',
                expected: '...',
            },
        ],
    },
    {
        name: 'readmatrix',
        category: 'io',
        status: 'unsupported',
        effect: 'effectful',
        cases: [
            {
                id: 'readmatrix.csv',
                kind: 'gap',
                input: "readmatrix('x.csv')",
                expected: 'UnsupportedOperation',
            },
        ],
    },
    {
        name: 'parfor',
        category: 'control',
        status: 'unsupported',
        effect: 'stateful',
        notes: 'SILENT WRONG: parfor i=1:2, i, end → i (same strip as for)',
        cases: [
            {
                id: 'parfor.strip',
                kind: 'gap',
                input: 'parfor i=1:2, i, end',
                expected: '2',
                notes: 'currently returns i',
            },
        ],
    },
    // --- wave 5: @-strip / command keywords / ODE family / array / toolbox ---
    {
        name: 'bsxfun',
        category: 'array',
        status: 'unsupported',
        effect: 'pure',
        notes: 'SILENT WRONG: @ stripped — bsxfun(@plus,…) → bsxfun(plus,…)',
        cases: [
            {
                id: 'bsxfun.plus',
                kind: 'gap',
                input: 'bsxfun(@plus, [1, 2], [3; 4])',
                expected: '[4, 5; 5, 6]',
                notes: 'currently bsxfun(plus, …)',
            },
        ],
    },
    {
        name: 'arrayfun',
        category: 'array',
        status: 'unsupported',
        effect: 'pure',
        notes: '@ stripped to bare sin',
        cases: [
            {
                id: 'arrayfun.sin',
                kind: 'gap',
                input: 'arrayfun(@sin, [0, pi/2])',
                expected: '[0, 1]',
            },
        ],
    },
    {
        name: 'cellfun',
        category: 'array',
        status: 'unsupported',
        effect: 'pure',
        notes: 'SILENT WRONG: @ and cell both strip — cellfun(@numel,{1,2}) → cellfun(numel, 1, 2)',
        cases: [
            {
                id: 'cellfun.numel',
                kind: 'gap',
                input: 'cellfun(@numel, {1, 2})',
                expected: '[1, 1]',
            },
        ],
    },
    {
        name: 'hold_on',
        category: 'plot',
        status: 'unsupported',
        effect: 'effectful',
        notes: 'SILENT WRONG: hold on → on (command keyword stripped)',
        cases: [
            {
                id: 'hold.on',
                kind: 'gap',
                input: 'hold on',
                expected: '...',
                notes: 'currently returns on',
            },
        ],
    },
    {
        name: 'grid_on',
        category: 'plot',
        status: 'unsupported',
        effect: 'effectful',
        notes: 'SILENT WRONG: grid on → on',
        cases: [
            {
                id: 'grid.on',
                kind: 'gap',
                input: 'grid on',
                expected: '...',
                notes: 'currently returns on',
            },
        ],
    },
    {
        name: 'axis',
        category: 'plot',
        status: 'unsupported',
        effect: 'effectful',
        notes: 'SILENT WRONG: axis equal → equal',
        cases: [
            {
                id: 'axis.equal',
                kind: 'gap',
                input: 'axis equal',
                expected: '...',
                notes: 'currently returns equal',
            },
        ],
    },
    {
        name: 'profile',
        category: 'meta',
        status: 'unsupported',
        effect: 'effectful',
        notes: 'SILENT WRONG: profile on → on',
        cases: [
            {
                id: 'profile.on',
                kind: 'gap',
                input: 'profile on',
                expected: '...',
                notes: 'currently returns on',
            },
        ],
    },
    {
        name: 'dbstop',
        category: 'meta',
        status: 'unsupported',
        effect: 'effectful',
        notes: 'SILENT WRONG: dbstop if error → error',
        cases: [
            {
                id: 'dbstop.if_error',
                kind: 'gap',
                input: 'dbstop if error',
                expected: '...',
                notes: 'currently returns error',
            },
        ],
    },
    {
        name: 'ode15s',
        category: 'ode',
        status: 'unsupported',
        effect: 'pure',
        notes: 'SILENT WRONG: ode15s(@(t,y)y,[0,1],1) → 1',
        cases: [
            {
                id: 'ode15s.strip',
                kind: 'gap',
                input: 'ode15s(@(t,y)y, [0, 1], 1)',
                expected: '...',
                notes: 'currently returns 1',
            },
        ],
    },
    {
        name: 'ode113',
        category: 'ode',
        status: 'unsupported',
        effect: 'pure',
        notes: 'SILENT WRONG: same last-arg strip as ode45',
        cases: [
            {
                id: 'ode113.strip',
                kind: 'gap',
                input: 'ode113(@(t,y)y, [0, 1], 1)',
                expected: '...',
                notes: 'currently returns 1',
            },
        ],
    },
    {
        name: 'dde23',
        category: 'ode',
        status: 'unsupported',
        effect: 'pure',
        notes: 'SILENT WRONG: dde23(…) → [0, 2] (last arg)',
        cases: [
            {
                id: 'dde23.strip',
                kind: 'gap',
                input: 'dde23(@(t,y,z)z, [1], 1, [0, 2])',
                expected: '...',
                notes: 'currently returns [0, 2]',
            },
        ],
    },
    {
        name: 'fminsearch',
        category: 'solve',
        status: 'unsupported',
        effect: 'pure',
        notes: '@ handle stripped like fzero',
        cases: [
            {
                id: 'fminsearch.x2',
                kind: 'gap',
                input: 'fminsearch(@(x)x^2, 1)',
                expected: '0',
            },
        ],
    },
    {
        name: 'quadgk',
        category: 'calculus',
        status: 'unsupported',
        effect: 'pure',
        notes: '@ stripped to quadgk(x, sin(x), 0, pi)',
        cases: [
            {
                id: 'quadgk.sin',
                kind: 'gap',
                input: 'quadgk(@(x)sin(x), 0, pi)',
                expected: '2',
            },
        ],
    },
    {
        name: 'containers_Map',
        category: 'types',
        status: 'unsupported',
        effect: 'pure',
        notes: 'SILENT WRONG: containers.Map → Map (package path stripped)',
        cases: [
            {
                id: 'containers.map',
                kind: 'gap',
                input: 'containers.Map',
                expected: 'containers.Map',
                notes: 'currently returns Map',
            },
        ],
    },
    {
        name: 'py_list',
        category: 'interop',
        status: 'unsupported',
        effect: 'pure',
        notes: 'SILENT WRONG: py.list([1,2]) → list([1, 2])',
        cases: [
            {
                id: 'py.list',
                kind: 'gap',
                input: 'py.list([1, 2])',
                expected: '...',
                notes: 'currently list([1, 2])',
            },
        ],
    },
    {
        name: 'classdef',
        category: 'oop',
        status: 'unsupported',
        effect: 'stateful',
        notes: 'SILENT WRONG: classdef Foo, end → Foo',
        cases: [
            {
                id: 'classdef.foo',
                kind: 'gap',
                input: 'classdef Foo, end',
                expected: '...',
                notes: 'currently returns Foo',
            },
        ],
    },
    {
        name: 'spmd',
        category: 'parallel',
        status: 'unsupported',
        effect: 'stateful',
        notes: 'SILENT WRONG: spmd, 1, end → 1',
        cases: [
            {
                id: 'spmd.strip',
                kind: 'gap',
                input: 'spmd, 1, end',
                expected: '...',
                notes: 'currently returns 1',
            },
        ],
    },
    {
        name: 'iscell',
        category: 'types',
        status: 'unsupported',
        effect: 'pure',
        notes: 'SILENT WRONG: iscell({1}) → iscell(1) (brace cell stripped first)',
        cases: [
            {
                id: 'iscell.brace',
                kind: 'gap',
                input: 'iscell({1})',
                expected: '1',
                notes: 'currently iscell(1)',
            },
        ],
    },
    {
        name: 'all',
        category: 'array',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'all.true', kind: 'gap', input: 'all([1, 1])', expected: '1' }],
    },
    {
        name: 'any',
        category: 'array',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'any.mixed', kind: 'gap', input: 'any([0, 1])', expected: '1' }],
    },
    {
        name: 'find',
        category: 'array',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'find.mask', kind: 'gap', input: 'find([0, 1, 0])', expected: '2' }],
    },
    {
        name: 'unique',
        category: 'array',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'unique.112', kind: 'gap', input: 'unique([1, 1, 2])', expected: '[1, 2]' }],
    },
    {
        name: 'repmat',
        category: 'array',
        status: 'unsupported',
        effect: 'pure',
        cases: [
            {
                id: 'repmat.21',
                kind: 'gap',
                input: 'repmat([1, 2], 2, 1)',
                expected: '[1, 2; 1, 2]',
            },
        ],
    },
    {
        name: 'tril',
        category: 'matrix',
        status: 'unsupported',
        effect: 'pure',
        cases: [
            {
                id: 'tril.2x2',
                kind: 'gap',
                input: 'tril([1, 2; 3, 4])',
                expected: '[1, 0; 3, 4]',
            },
        ],
    },
    {
        name: 'qr',
        category: 'linear_algebra',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'qr.2x2', kind: 'gap', input: 'qr([1, 2; 3, 4])', expected: '...' }],
    },
    {
        name: 'lu',
        category: 'linear_algebra',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'lu.2x2', kind: 'gap', input: 'lu([1, 2; 3, 4])', expected: '...' }],
    },
    {
        name: 'chol',
        category: 'linear_algebra',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'chol.spd', kind: 'gap', input: 'chol([2, 1; 1, 2])', expected: '...' }],
    },
    {
        name: 'expm',
        category: 'linear_algebra',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'expm.rot', kind: 'gap', input: 'expm([0, 1; -1, 0])', expected: '...' }],
    },
    {
        name: 'floor',
        category: 'numeric',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'floor.2_7', kind: 'gap', input: 'floor(2.7)', expected: '2' }],
    },
    {
        name: 'mod',
        category: 'numeric',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'mod.10_3', kind: 'gap', input: 'mod(10, 3)', expected: '1' }],
    },
    {
        name: 'hypot',
        category: 'numeric',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'hypot.34', kind: 'gap', input: 'hypot(3, 4)', expected: '5' }],
    },
    {
        name: 'inf',
        category: 'constant',
        status: 'partial',
        effect: 'pure',
        notes: 'symbol retained; no Inf arithmetic contract yet',
        cases: [{ id: 'inf.atom', kind: 'eval', input: 'inf', expected: 'inf' }],
    },
    {
        name: 'NaN',
        category: 'constant',
        status: 'partial',
        effect: 'pure',
        cases: [{ id: 'NaN.capital', kind: 'eval', input: 'NaN', expected: 'NaN' }],
    },
    {
        name: 'rand',
        category: 'random',
        status: 'unsupported',
        effect: 'effectful',
        cases: [{ id: 'rand.2', kind: 'gap', input: 'rand(2)', expected: '...' }],
    },
    {
        name: 'hilb',
        category: 'matrix',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'hilb.3', kind: 'gap', input: 'hilb(3)', expected: '...' }],
    },
    {
        name: 'sym',
        category: 'symbolic',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'sym.x', kind: 'gap', input: "sym('x')", expected: 'x' }],
    },
    {
        name: 'vpa',
        category: 'symbolic',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'vpa.pi', kind: 'gap', input: 'vpa(pi, 10)', expected: '3.141592654' }],
    },
    {
        name: 'jsondecode',
        category: 'io',
        status: 'unsupported',
        effect: 'pure',
        cases: [
            {
                id: 'jsondecode.obj',
                kind: 'gap',
                input: "jsondecode('{\"a\":1}')",
                expected: '...',
            },
        ],
    },
    {
        name: 'sprintf',
        category: 'string',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'sprintf.d', kind: 'gap', input: "sprintf('%d', 1)", expected: "'1'" }],
    },
    {
        name: 'legend',
        category: 'plot',
        status: 'unsupported',
        effect: 'effectful',
        cases: [{ id: 'legend.a', kind: 'gap', input: "legend('a')", expected: '...' }],
    },
    {
        name: 'subplot',
        category: 'plot',
        status: 'unsupported',
        effect: 'effectful',
        cases: [{ id: 'subplot.121', kind: 'gap', input: 'subplot(1, 2, 1)', expected: '...' }],
    },
    // --- wave 6: logic ops / assignment / strings / symbolic / interop ---
    {
        name: 'and',
        category: 'logic',
        status: 'supported',
        effect: 'pure',
        notes: 'numeric short-circuit style && on 0/1',
        cases: [{ id: 'and.10', kind: 'eval', input: '1 && 0', expected: 'false' }],
    },
    {
        name: 'or',
        category: 'logic',
        status: 'supported',
        effect: 'pure',
        cases: [{ id: 'or.10', kind: 'eval', input: '1 || 0', expected: 'true' }],
    },
    {
        name: 'not',
        category: 'logic',
        status: 'supported',
        effect: 'pure',
        cases: [
            { id: 'not.1', kind: 'eval', input: '~1', expected: 'false' },
            { id: 'not.0', kind: 'eval', input: '~0', expected: 'true' },
        ],
    },
    {
        name: 'xor',
        category: 'logic',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'xor.10', kind: 'gap', input: 'xor(1, 0)', expected: '1' }],
    },
    {
        name: 'bitand',
        category: 'bitwise',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'bitand.63', kind: 'gap', input: 'bitand(6, 3)', expected: '2' }],
    },
    {
        name: 'subsasgn',
        category: 'session',
        status: 'unsupported',
        effect: 'stateful',
        notes: 'SILENT WRONG: indexed / grow assignment does not persist; A=[]; A(1)=1; A → A; A(3,3)=1 after zeros → A; end+1 / end-1 often oak error',
        cases: [
            {
                id: 'subsasgn.vec',
                kind: 'gap',
                input: 'A=[1, 2, 3]; A(2)=9; A',
                expected: '[1, 9, 3]',
                notes: 'currently returns A',
            },
            {
                id: 'subsasgn.grow',
                kind: 'gap',
                input: 'A=zeros(2); A(3, 3)=1; A',
                expected: '...',
                notes: 'currently returns A',
            },
            {
                id: 'subsasgn.end_plus',
                kind: 'gap',
                input: 'B=1:4; B(end+1)=5',
                expected: '[1, 2, 3, 4, 5]',
                notes: 'oak error node',
            },
        ],
    },
    {
        name: 'deal',
        category: 'session',
        status: 'unsupported',
        effect: 'pure',
        notes: 'multi-assign [a,b]=deal(1,2) does not bind; [~,b]=max(...) oak error',
        cases: [
            {
                id: 'deal.multi',
                kind: 'gap',
                input: '[a, b]=deal(1, 2)',
                expected: '...',
                notes: 'currently returns deal(1, 2)',
            },
        ],
    },
    {
        name: 'strcat',
        category: 'string',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'strcat.ab', kind: 'gap', input: "strcat('a', 'b')", expected: "'ab'" }],
    },
    {
        name: 'strcmp',
        category: 'string',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'strcmp.eq', kind: 'gap', input: "strcmp('a', 'a')", expected: '1' }],
    },
    {
        name: 'strjoin',
        category: 'string',
        status: 'unsupported',
        effect: 'pure',
        notes: 'SILENT WRONG: cell brace stripped — strjoin({\'a\',\'b\'},\',\') → strjoin(\'a\', \'b\', \',\')',
        cases: [
            {
                id: 'strjoin.ab',
                kind: 'gap',
                input: "strjoin({'a', 'b'}, ',')",
                expected: "'a,b'",
            },
        ],
    },
    {
        name: 'missing',
        category: 'types',
        status: 'partial',
        effect: 'pure',
        notes: 'atom retained; ismissing/rmmissing unevaluated',
        cases: [{ id: 'missing.atom', kind: 'eval', input: 'missing', expected: 'missing' }],
    },
    {
        name: 'ismissing',
        category: 'types',
        status: 'unsupported',
        effect: 'pure',
        cases: [
            {
                id: 'ismissing.missing',
                kind: 'gap',
                input: 'ismissing(missing)',
                expected: '1',
            },
        ],
    },
    {
        name: 'lsqcurvefit',
        category: 'solve',
        status: 'unsupported',
        effect: 'pure',
        notes: 'SILENT WRONG: @ stripped and result collapses to last arg [1,2]',
        cases: [
            {
                id: 'lsqcurvefit.strip',
                kind: 'gap',
                input: 'lsqcurvefit(@(x,xdata)x*xdata, 1, [1, 2], [1, 2])',
                expected: '1',
                notes: 'currently returns [1, 2]',
            },
        ],
    },
    {
        name: 'fminbnd',
        category: 'solve',
        status: 'unsupported',
        effect: 'pure',
        notes: '@ handle stripped',
        cases: [
            {
                id: 'fminbnd.x2',
                kind: 'gap',
                input: 'fminbnd(@(x)x^2, -1, 1)',
                expected: '0',
            },
        ],
    },
    {
        name: 'syms',
        category: 'symbolic',
        status: 'unsupported',
        effect: 'stateful',
        notes: 'SILENT WRONG: syms x → x (declaration stripped like global)',
        cases: [
            {
                id: 'syms.strip',
                kind: 'gap',
                input: 'syms x',
                expected: '...',
                notes: 'currently returns x',
            },
        ],
    },
    {
        name: 'expand',
        category: 'symbolic',
        status: 'unsupported',
        effect: 'pure',
        notes: 'args already wrongly powered: expand((x+1)^2) sees expand(1+x^2)',
        cases: [
            {
                id: 'expand.binomsq',
                kind: 'gap',
                input: 'expand((x + 1)^2)',
                expected: 'x^2 + 2*x + 1',
            },
        ],
    },
    {
        name: 'limit',
        category: 'symbolic',
        status: 'unsupported',
        effect: 'pure',
        cases: [
            {
                id: 'limit.sinc',
                kind: 'gap',
                input: 'limit(sin(x)/x, x, 0)',
                expected: '1',
            },
        ],
    },
    {
        name: 'dsolve',
        category: 'symbolic',
        status: 'planned',
        effect: 'pure',
        cases: [
            {
                id: 'dsolve.exp',
                kind: 'gap',
                input: 'dsolve(diff(y)==y)',
                expected: 'C1*exp(t)',
            },
        ],
    },
    {
        name: 'eval',
        category: 'meta',
        status: 'unsupported',
        effect: 'effectful',
        cases: [{ id: 'eval.plus', kind: 'gap', input: "eval('1+1')", expected: '2' }],
    },
    {
        name: 'feval',
        category: 'meta',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'feval.sin', kind: 'gap', input: "feval('sin', 0)", expected: '0' }],
    },
    {
        name: 'func2str',
        category: 'meta',
        status: 'unsupported',
        effect: 'pure',
        notes: '@ stripped: func2str(@sin) → func2str(sin)',
        cases: [{ id: 'func2str.sin', kind: 'gap', input: 'func2str(@sin)', expected: "'sin'" }],
    },
    {
        name: 'pwd',
        category: 'io',
        status: 'unsupported',
        effect: 'effectful',
        cases: [{ id: 'pwd.basic', kind: 'gap', input: 'pwd', expected: '...' }],
    },
    {
        name: 'exist',
        category: 'meta',
        status: 'unsupported',
        effect: 'pure',
        cases: [
            {
                id: 'exist.sin',
                kind: 'gap',
                input: "exist('sin', 'builtin')",
                expected: '5',
            },
        ],
    },
    {
        name: 'fullfile',
        category: 'io',
        status: 'unsupported',
        effect: 'pure',
        cases: [
            {
                id: 'fullfile.ab',
                kind: 'gap',
                input: "fullfile('a', 'b')",
                expected: '...',
            },
        ],
    },
    {
        name: 'py_math_sqrt',
        category: 'interop',
        status: 'unsupported',
        effect: 'pure',
        notes: 'SILENT WRONG: py.math.sqrt(4) and math.sqrt(4) both collapse to matlab sqrt → 2',
        cases: [
            {
                id: 'py.math.sqrt',
                kind: 'gap',
                input: 'py.math.sqrt(4)',
                expected: '...',
                notes: 'currently returns 2 via path strip to sqrt',
            },
        ],
    },
    {
        name: 'uifigure',
        category: 'ui',
        status: 'unsupported',
        effect: 'effectful',
        cases: [{ id: 'uifigure.basic', kind: 'gap', input: 'uifigure', expected: '...' }],
    },
    {
        name: 'msgbox',
        category: 'ui',
        status: 'unsupported',
        effect: 'effectful',
        cases: [{ id: 'msgbox.a', kind: 'gap', input: "msgbox('a')", expected: '...' }],
    },
    // --- wave 7: IEEE / bitwise | / colon / commands / simplify win ---
    {
        name: 'ieee_edge',
        category: 'numeric',
        status: 'partial',
        effect: 'pure',
        notes: 'SILENT WRONG: 0/0→0 and Inf-Inf→0 (MATLAB expects NaN); 0^0→1 matches MATLAB',
        cases: [
            {
                id: 'ieee.0over0',
                kind: 'gap',
                input: '0/0',
                expected: 'NaN',
                notes: 'currently 0',
            },
            {
                id: 'ieee.inf_minus_inf',
                kind: 'gap',
                input: 'Inf - Inf',
                expected: 'NaN',
                notes: 'currently 0',
            },
            {
                id: 'ieee.0pow0',
                kind: 'eval',
                input: '0^0',
                expected: '1',
                notes: 'MATLAB-compatible',
            },
        ],
    },
    {
        name: 'bitor_op',
        category: 'logic',
        status: 'unsupported',
        effect: 'pure',
        notes: 'SILENT WRONG: 1|0 → 0 (expect 1); [1,0]|[0,1] → [0,1] (expect [1,1])',
        cases: [
            {
                id: 'bitor.scalar',
                kind: 'gap',
                input: '1 | 0',
                expected: '1',
                notes: 'currently 0',
            },
            {
                id: 'bitor.vec',
                kind: 'gap',
                input: '[1, 0] | [0, 1]',
                expected: '[1, 1]',
                notes: 'currently [0, 1]',
            },
        ],
    },
    {
        name: 'bitand_op',
        category: 'logic',
        status: 'partial',
        effect: 'pure',
        notes: 'scalar 1&0 → false OK; vector [1,0]&[1,1] → [1,1] SILENT WRONG (expect [1,0])',
        cases: [
            { id: 'bitand.scalar', kind: 'eval', input: '1 & 0', expected: 'false' },
            {
                id: 'bitand.vec',
                kind: 'gap',
                input: '[1, 0] & [1, 1]',
                expected: '[1, 0]',
                notes: 'currently [1, 1]',
            },
        ],
    },
    {
        name: 'colon_all',
        category: 'indexing',
        status: 'unsupported',
        effect: 'pure',
        notes: 'SILENT WRONG: A(:) → A()',
        cases: [
            {
                id: 'colon.all',
                kind: 'gap',
                input: 'A=[1, 2; 3, 4]; A(:)',
                expected: '[1; 3; 2; 4]',
                notes: 'currently A()',
            },
        ],
    },
    {
        name: 'end_minus',
        category: 'indexing',
        status: 'unsupported',
        effect: 'pure',
        notes: 'oak error on A(end-1) and A(1:2:end)',
        cases: [
            {
                id: 'end.minus1',
                kind: 'gap',
                input: 'A=[1, 2, 3]; A(end-1)',
                expected: '2',
            },
        ],
    },
    {
        name: 'plus_eq',
        category: 'session',
        status: 'unsupported',
        effect: 'stateful',
        notes: 'oak error on x+=1 and A(1)+=1',
        cases: [{ id: 'pluseq.x', kind: 'gap', input: 'x=1; x+=1', expected: '2' }],
    },
    {
        name: 'close_all',
        category: 'plot',
        status: 'unsupported',
        effect: 'effectful',
        notes: 'SILENT WRONG: close all → all',
        cases: [
            {
                id: 'close.all',
                kind: 'gap',
                input: 'close all',
                expected: '...',
                notes: 'currently returns all',
            },
        ],
    },
    {
        name: 'hold_off',
        category: 'plot',
        status: 'unsupported',
        effect: 'effectful',
        notes: 'SILENT WRONG: hold off → off',
        cases: [
            {
                id: 'hold.off',
                kind: 'gap',
                input: 'hold off',
                expected: '...',
                notes: 'currently returns off',
            },
        ],
    },
    {
        name: 'colormap',
        category: 'plot',
        status: 'unsupported',
        effect: 'effectful',
        notes: 'SILENT WRONG: colormap jet → jet',
        cases: [
            {
                id: 'colormap.jet',
                kind: 'gap',
                input: 'colormap jet',
                expected: '...',
                notes: 'currently returns jet',
            },
        ],
    },
    {
        name: 'format',
        category: 'meta',
        status: 'unsupported',
        effect: 'effectful',
        notes: 'SILENT WRONG: format long → long',
        cases: [
            {
                id: 'format.long',
                kind: 'gap',
                input: 'format long',
                expected: '...',
                notes: 'currently returns long',
            },
        ],
    },
    {
        name: 'simplify_trig',
        category: 'symbolic',
        status: 'supported',
        effect: 'pure',
        notes: 'same identity as simplify entry; explicit symbolic toolbox spelling',
        cases: [
            {
                id: 'simplify_trig.pythag',
                kind: 'eval',
                input: 'simplify(sin(x)^2 + cos(x)^2)',
                expected: '1',
            },
        ],
    },
    {
        name: 'isequal',
        category: 'comparison',
        status: 'unsupported',
        effect: 'pure',
        cases: [
            {
                id: 'isequal.vec',
                kind: 'gap',
                input: 'isequal([1, 2], [1, 2])',
                expected: '1',
            },
        ],
    },
    {
        name: 'lt_chain',
        category: 'comparison',
        status: 'partial',
        effect: 'pure',
        notes: 'scalar 1<2<3 via Athena compare chain; elementwise vector Less still open',
        cases: [
            {
                id: 'ltchain.123',
                kind: 'eval',
                input: '1 < 2 < 3',
                expected: 'true',
            },
            {
                id: 'ltchain.vec',
                kind: 'gap',
                input: '[1, 2, 3] < 2',
                expected: '[1, 0, 0]',
            },
        ],
    },
    {
        name: 'odeset',
        category: 'ode',
        status: 'unsupported',
        effect: 'pure',
        notes: 'SILENT WRONG: ode45(..., odeset(...)) collapses to odeset(...) last arg',
        cases: [
            {
                id: 'odeset.strip',
                kind: 'gap',
                input: "ode45(@(t,y)y, [0, 1], 1, odeset('RelTol', 1e-3))",
                expected: '...',
                notes: "currently returns odeset('RelTol', 0.001)",
            },
        ],
    },
    {
        name: 'rref',
        category: 'linear_algebra',
        status: 'unsupported',
        effect: 'pure',
        cases: [
            {
                id: 'rref.basic',
                kind: 'gap',
                input: 'rref([1, 2, 3; 4, 5, 6])',
                expected: '...',
            },
        ],
    },
    {
        name: 'conv',
        category: 'signal',
        status: 'unsupported',
        effect: 'pure',
        cases: [
            {
                id: 'conv.basic',
                kind: 'gap',
                input: 'conv([1, 1], [1, -1])',
                expected: '[1, 0, -1]',
            },
        ],
    },
    {
        name: 'polyder',
        category: 'polynomial',
        status: 'unsupported',
        effect: 'pure',
        cases: [
            {
                id: 'polyder.quad',
                kind: 'gap',
                input: 'polyder([1, 2, 1])',
                expected: '[2, 2]',
            },
        ],
    },
    {
        name: 'scatter',
        category: 'plot',
        status: 'unsupported',
        effect: 'effectful',
        cases: [
            {
                id: 'scatter.basic',
                kind: 'gap',
                input: 'scatter([1, 2], [3, 4])',
                expected: '<svg',
            },
        ],
    },
    {
        name: 'bar',
        category: 'plot',
        status: 'unsupported',
        effect: 'effectful',
        cases: [{ id: 'bar.3', kind: 'gap', input: 'bar([1, 2, 3])', expected: '<svg' }],
    },
    {
        name: 'fourier_sym',
        category: 'symbolic',
        status: 'unsupported',
        effect: 'pure',
        notes: 'SILENT WRONG: fourier(exp(-x^2)) → fourier(exp(x^2)) sign flip',
        cases: [
            {
                id: 'fourier.gauss_sign',
                kind: 'gap',
                input: 'fourier(exp(-x^2))',
                expected: '...',
                notes: 'currently fourier(exp(x^2))',
            },
        ],
    },
    {
        name: 'methods_meta',
        category: 'meta',
        status: 'unsupported',
        effect: 'pure',
        notes: "SILENT WRONG: methods('double') → 'double'",
        cases: [
            {
                id: 'methods.double',
                kind: 'gap',
                input: "methods('double')",
                expected: '...',
                notes: "currently returns 'double'",
            },
        ],
    },
    // --- wave 8: bool | / complex literal / set / fft / builtin ---
    {
        name: 'true_bitor',
        category: 'logic',
        status: 'unsupported',
        effect: 'pure',
        notes: 'SILENT WRONG: true | false → false (same bug as 1|0)',
        cases: [
            {
                id: 'true.bitor',
                kind: 'gap',
                input: 'true | false',
                expected: '1',
                notes: 'currently false',
            },
        ],
    },
    {
        name: 'true_bitand',
        category: 'logic',
        status: 'partial',
        effect: 'pure',
        notes: 'true & false → false OK; true && false stays And(true,false) unevaluated',
        cases: [
            { id: 'true.bitand', kind: 'eval', input: 'true & false', expected: 'false' },
            {
                id: 'true.and_sc',
                kind: 'gap',
                input: 'true && false',
                expected: '0',
                notes: 'currently And(true, false)',
            },
        ],
    },
    {
        name: 'i_squared',
        category: 'numeric',
        status: 'unsupported',
        effect: 'pure',
        notes: 'bare i/j symbols retained; 1+2i / 1i still oak bad literal',
        cases: [
            { id: 'i.sq', kind: 'gap', input: 'i^2', expected: '-1' },
            { id: 'j.sq', kind: 'gap', input: 'j^2', expected: '-1' },
        ],
    },
    {
        name: 'logical',
        category: 'types',
        status: 'unsupported',
        effect: 'pure',
        cases: [
            {
                id: 'logical.vec',
                kind: 'gap',
                input: 'logical([1, 0, 2])',
                expected: '[1, 0, 1]',
            },
        ],
    },
    {
        name: 'intersect',
        category: 'array',
        status: 'unsupported',
        effect: 'pure',
        cases: [
            {
                id: 'intersect.basic',
                kind: 'gap',
                input: 'intersect([1, 2, 3], [2, 3, 4])',
                expected: '[2, 3]',
            },
        ],
    },
    {
        name: 'union',
        category: 'array',
        status: 'unsupported',
        effect: 'pure',
        cases: [
            {
                id: 'union.basic',
                kind: 'gap',
                input: 'union([1, 2], [2, 3])',
                expected: '[1, 2, 3]',
            },
        ],
    },
    {
        name: 'setdiff',
        category: 'array',
        status: 'unsupported',
        effect: 'pure',
        cases: [
            {
                id: 'setdiff.basic',
                kind: 'gap',
                input: 'setdiff([1, 2, 3], [2])',
                expected: '[1, 3]',
            },
        ],
    },
    {
        name: 'ismember',
        category: 'array',
        status: 'unsupported',
        effect: 'pure',
        cases: [
            {
                id: 'ismember.2',
                kind: 'gap',
                input: 'ismember([1, 2, 3], 2)',
                expected: '[0, 1, 0]',
            },
        ],
    },
    {
        name: 'ifft',
        category: 'signal',
        status: 'unsupported',
        effect: 'pure',
        cases: [
            {
                id: 'ifft.roundtrip',
                kind: 'gap',
                input: 'ifft(fft([1, 2, 3, 4]))',
                expected: '[1, 2, 3, 4]',
            },
        ],
    },
    {
        name: 'filter',
        category: 'signal',
        status: 'unsupported',
        effect: 'pure',
        cases: [
            {
                id: 'filter.basic',
                kind: 'gap',
                input: 'filter([1], [1, -0.5], ones(1, 5))',
                expected: '...',
            },
        ],
    },
    {
        name: 'conv2',
        category: 'signal',
        status: 'unsupported',
        effect: 'pure',
        cases: [
            {
                id: 'conv2.basic',
                kind: 'gap',
                input: 'conv2([1, 2; 3, 4], [1, 1; 1, 1])',
                expected: '...',
            },
        ],
    },
    {
        name: 'blkdiag',
        category: 'matrix',
        status: 'unsupported',
        effect: 'pure',
        cases: [
            {
                id: 'blkdiag.eye3',
                kind: 'gap',
                input: 'blkdiag(eye(2), 3)',
                expected: '...',
            },
        ],
    },
    {
        name: 'randperm',
        category: 'random',
        status: 'unsupported',
        effect: 'effectful',
        cases: [{ id: 'randperm.5', kind: 'gap', input: 'randperm(5)', expected: '...' }],
    },
    {
        name: 'builtin',
        category: 'meta',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'builtin.sin', kind: 'gap', input: "builtin('sin', 0)", expected: '0' }],
    },
    {
        name: 'char',
        category: 'string',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'char.65', kind: 'gap', input: 'char(65)', expected: "'A'" }],
    },
    {
        name: 'semilogx',
        category: 'plot',
        status: 'unsupported',
        effect: 'effectful',
        cases: [
            {
                id: 'semilogx.basic',
                kind: 'gap',
                input: 'semilogx(1:3, 1:3)',
                expected: '<svg',
            },
        ],
    },
    {
        name: 'loglog',
        category: 'plot',
        status: 'unsupported',
        effect: 'effectful',
        cases: [
            {
                id: 'loglog.basic',
                kind: 'gap',
                input: 'loglog(1:3, 1:3)',
                expected: '<svg',
            },
        ],
    },
    {
        name: 'pie',
        category: 'plot',
        status: 'unsupported',
        effect: 'effectful',
        cases: [{ id: 'pie.3', kind: 'gap', input: 'pie([1, 2, 3])', expected: '<svg' }],
    },
    {
        name: 'warndlg',
        category: 'ui',
        status: 'unsupported',
        effect: 'effectful',
        cases: [{ id: 'warndlg.w', kind: 'gap', input: "warndlg('w')", expected: '...' }],
    },
    {
        name: 'latex_sym',
        category: 'symbolic',
        status: 'unsupported',
        effect: 'pure',
        cases: [
            {
                id: 'latex.x2',
                kind: 'gap',
                input: "latex(sym('x^2'))",
                expected: '...',
            },
        ],
    },
    // --- wave 9: colon step / ++ / package strip / predicates / sparse ---
    {
        name: 'preincrement',
        category: 'session',
        status: 'unsupported',
        effect: 'stateful',
        notes: 'SILENT WRONG: ++A → A; A++ oak error',
        cases: [
            {
                id: 'preinc.A',
                kind: 'gap',
                input: '++A',
                expected: '...',
                notes: 'currently returns A',
            },
        ],
    },
    {
        name: 'gpuArray_zeros',
        category: 'interop',
        status: 'unsupported',
        effect: 'pure',
        notes: 'SILENT WRONG: gpuArray.zeros(2) → zeros(2) (package path stripped)',
        cases: [
            {
                id: 'gpuarray.zeros',
                kind: 'gap',
                input: 'gpuArray.zeros(2)',
                expected: '...',
                notes: 'currently zeros(2)',
            },
        ],
    },
    {
        name: 'coder_typeof',
        category: 'interop',
        status: 'unsupported',
        effect: 'pure',
        notes: 'SILENT WRONG: coder.typeof(1) → typeof(1)',
        cases: [
            {
                id: 'coder.typeof',
                kind: 'gap',
                input: 'coder.typeof(1)',
                expected: '...',
                notes: 'currently typeof(1)',
            },
        ],
    },
    {
        name: 'hex2dec',
        category: 'numeric',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'hex2dec.ff', kind: 'gap', input: "hex2dec('FF')", expected: '255' }],
    },
    {
        name: 'dec2hex',
        category: 'numeric',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'dec2hex.255', kind: 'gap', input: 'dec2hex(255)', expected: "'FF'" }],
    },
    {
        name: 'isempty',
        category: 'types',
        status: 'unsupported',
        effect: 'pure',
        cases: [
            { id: 'isempty.empty', kind: 'gap', input: 'isempty([])', expected: '1' },
            { id: 'isempty.zero', kind: 'gap', input: 'isempty(0)', expected: '0' },
        ],
    },
    {
        name: 'isscalar',
        category: 'types',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'isscalar.1', kind: 'gap', input: 'isscalar(1)', expected: '1' }],
    },
    {
        name: 'isvector',
        category: 'types',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'isvector.row', kind: 'gap', input: 'isvector([1, 2])', expected: '1' }],
    },
    {
        name: 'isrow',
        category: 'types',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'isrow.12', kind: 'gap', input: 'isrow([1, 2])', expected: '1' }],
    },
    {
        name: 'iscolumn',
        category: 'types',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'iscolumn.12', kind: 'gap', input: 'iscolumn([1; 2])', expected: '1' }],
    },
    {
        name: 'numel',
        category: 'matrix',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'numel.empty', kind: 'gap', input: 'numel([])', expected: '0' }],
    },
    {
        name: 'nan_matrix',
        category: 'matrix',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'nan.2', kind: 'gap', input: 'nan(2)', expected: '[NaN, NaN; NaN, NaN]' }],
    },
    {
        name: 'inf_matrix',
        category: 'matrix',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'inf.2', kind: 'gap', input: 'inf(2)', expected: '...' }],
    },
    {
        name: 'true_matrix',
        category: 'matrix',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'true.23', kind: 'gap', input: 'true(2, 3)', expected: '...' }],
    },
    {
        name: 'speye',
        category: 'matrix',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'speye.3', kind: 'gap', input: 'speye(3)', expected: '...' }],
    },
    {
        name: 'nnz',
        category: 'matrix',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'nnz.speye2', kind: 'gap', input: 'nnz(speye(2))', expected: '2' }],
    },
    {
        name: 'accumarray',
        category: 'array',
        status: 'unsupported',
        effect: 'pure',
        cases: [
            {
                id: 'accumarray.basic',
                kind: 'gap',
                input: 'accumarray([1; 2; 1], [10; 20; 30])',
                expected: '[40; 20]',
            },
        ],
    },
    {
        name: 'logspace',
        category: 'matrix',
        status: 'unsupported',
        effect: 'pure',
        cases: [
            {
                id: 'logspace.3',
                kind: 'gap',
                input: 'logspace(0, 2, 3)',
                expected: '[1, 10, 100]',
            },
        ],
    },
    {
        name: 'normcdf',
        category: 'stats',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'normcdf.0', kind: 'gap', input: 'normcdf(0)', expected: '0.5' }],
    },
    // --- wave 10: package strip / empty shapes / is* matrix / log2 ---
    {
        name: 'matlab_lang_on',
        category: 'interop',
        status: 'unsupported',
        effect: 'pure',
        notes: 'SILENT WRONG: matlab.lang.OnOffSwitchState.on → on',
        cases: [
            {
                id: 'matlab.lang.on',
                kind: 'gap',
                input: 'matlab.lang.OnOffSwitchState.on',
                expected: '...',
                notes: 'currently returns on',
            },
        ],
    },
    {
        name: 'times_eq',
        category: 'session',
        status: 'unsupported',
        effect: 'stateful',
        notes: 'oak error on A.*=3 / A./=2 / x^=2',
        cases: [
            {
                id: 'timeseq.elem',
                kind: 'gap',
                input: 'A=[1, 2]; A.*=3',
                expected: '[3, 6]',
            },
        ],
    },
    {
        name: 'log2',
        category: 'numeric',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'log2.8', kind: 'gap', input: 'log2(8)', expected: '3' }],
    },
    {
        name: 'pow2',
        category: 'numeric',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'pow2.3', kind: 'gap', input: 'pow2(3)', expected: '8' }],
    },
    {
        name: 'nextpow2',
        category: 'numeric',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'nextpow2.5', kind: 'gap', input: 'nextpow2(5)', expected: '3' }],
    },
    {
        name: 'flintmax',
        category: 'constant',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'flintmax.atom', kind: 'gap', input: 'flintmax', expected: '...' }],
    },
    {
        name: 'zeros_empty',
        category: 'matrix',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'zeros.0x5', kind: 'gap', input: 'zeros(0, 5)', expected: 'zeros(0,5)' }],
    },
    {
        name: 'ones_empty',
        category: 'matrix',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'ones.5x0', kind: 'gap', input: 'ones(5, 0)', expected: 'ones(5,0)' }],
    },
    {
        name: 'eye_empty',
        category: 'matrix',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'eye.0', kind: 'gap', input: 'eye(0)', expected: '[]' }],
    },
    {
        name: 'isdiag',
        category: 'matrix',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'isdiag.eye', kind: 'gap', input: 'isdiag(eye(3))', expected: '1' }],
    },
    {
        name: 'issymmetric',
        category: 'matrix',
        status: 'unsupported',
        effect: 'pure',
        cases: [
            {
                id: 'issymmetric.eye',
                kind: 'gap',
                input: 'issymmetric(eye(3))',
                expected: '1',
            },
        ],
    },
    {
        name: 'istril',
        category: 'matrix',
        status: 'unsupported',
        effect: 'pure',
        cases: [
            {
                id: 'istril.tril',
                kind: 'gap',
                input: 'istril(tril(ones(3)))',
                expected: '1',
            },
        ],
    },
    {
        name: 'bitcmp',
        category: 'bitwise',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'bitcmp.u8', kind: 'gap', input: "bitcmp(1, 'uint8')", expected: '254' }],
    },
    {
        name: 'fillmissing',
        category: 'types',
        status: 'unsupported',
        effect: 'pure',
        cases: [
            {
                id: 'fillmissing.const',
                kind: 'gap',
                input: "fillmissing([1, NaN], 'constant', 0)",
                expected: '[1, 0]',
            },
        ],
    },
    {
        name: 'odeset_opts',
        category: 'ode',
        status: 'unsupported',
        effect: 'pure',
        notes: 'odeset itself echoes; scientific 1e-6 becomes decimal',
        cases: [
            {
                id: 'odeset.reltol',
                kind: 'gap',
                input: "odeset('RelTol', 1e-6)",
                expected: '...',
            },
        ],
    },
    {
        name: 'pcg',
        category: 'linear_algebra',
        status: 'unsupported',
        effect: 'pure',
        cases: [
            {
                id: 'pcg.eye',
                kind: 'gap',
                input: 'pcg(speye(3), ones(3, 1))',
                expected: '...',
            },
        ],
    },
    // --- wave 11: comparisons / sparse / solvers / strings / datetime / UI ---
    {
        name: 'eq_fn',
        category: 'comparison',
        status: 'unsupported',
        effect: 'pure',
        notes: 'functional eq([1,2],[1,2]) unevaluated; true==1 stays Equal head',
        cases: [
            {
                id: 'eq.fn_vec',
                kind: 'gap',
                input: 'eq([1, 2], [1, 2])',
                expected: '[1, 1]',
            },
            {
                id: 'eq.true_num',
                kind: 'gap',
                input: 'true == 1',
                expected: '1',
                notes: 'currently Equal(true, 1)',
            },
        ],
    },
    {
        name: 'isequaln',
        category: 'comparison',
        status: 'unsupported',
        effect: 'pure',
        cases: [
            {
                id: 'isequaln.nan',
                kind: 'gap',
                input: 'isequaln([NaN], [NaN])',
                expected: '1',
            },
        ],
    },
    {
        name: 'isnan',
        category: 'predicates',
        status: 'unsupported',
        effect: 'pure',
        cases: [
            { id: 'isnan.nan', kind: 'gap', input: 'isnan(NaN)', expected: '1' },
            { id: 'isnan.0', kind: 'gap', input: 'isnan(0)', expected: '0' },
        ],
    },
    {
        name: 'nan_eq',
        category: 'comparison',
        status: 'unsupported',
        effect: 'pure',
        notes: 'NaN==NaN / NaN~=NaN stay Equal/Unequal heads (IEEE unmet)',
        cases: [
            {
                id: 'nan.eq',
                kind: 'gap',
                input: 'NaN == NaN',
                expected: '0',
                notes: 'currently Equal(NaN, NaN)',
            },
            {
                id: 'nan.ne',
                kind: 'gap',
                input: 'NaN ~= NaN',
                expected: '1',
                notes: 'currently Unequal(NaN, NaN)',
            },
        ],
    },
    {
        name: 'isstring',
        category: 'types',
        status: 'unsupported',
        effect: 'pure',
        cases: [
            {
                id: 'isstring.dq',
                kind: 'gap',
                input: 'isstring("a")',
                expected: '1',
            },
            {
                id: 'isstring.sq',
                kind: 'gap',
                input: "isstring('a')",
                expected: '0',
            },
        ],
    },
    {
        name: 'ischar',
        category: 'types',
        status: 'unsupported',
        effect: 'pure',
        cases: [
            {
                id: 'ischar.sq',
                kind: 'gap',
                input: "ischar('a')",
                expected: '1',
            },
            {
                id: 'ischar.dq',
                kind: 'gap',
                input: 'ischar("a")',
                expected: '0',
            },
        ],
    },
    {
        name: 'string_plus',
        category: 'string',
        status: 'unsupported',
        effect: 'pure',
        cases: [
            {
                id: 'string.plus',
                kind: 'gap',
                input: '"hello" + "world"',
                expected: '"helloworld"',
            },
            {
                id: 'string.append',
                kind: 'gap',
                input: 'append("a", "b")',
                expected: '"ab"',
            },
        ],
    },
    {
        name: 'startsWith',
        category: 'string',
        status: 'unsupported',
        effect: 'pure',
        cases: [
            {
                id: 'startswith.a',
                kind: 'gap',
                input: 'startsWith("abc", "a")',
                expected: '1',
            },
        ],
    },
    {
        name: 'endsWith',
        category: 'string',
        status: 'unsupported',
        effect: 'pure',
        cases: [
            {
                id: 'endswith.c',
                kind: 'gap',
                input: 'endsWith("abc", "c")',
                expected: '1',
            },
        ],
    },
    {
        name: 'erase',
        category: 'string',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'erase.b', kind: 'gap', input: 'erase("abc", "b")', expected: '"ac"' }],
    },
    {
        name: 'extractAfter',
        category: 'string',
        status: 'unsupported',
        effect: 'pure',
        cases: [
            {
                id: 'extractafter.a',
                kind: 'gap',
                input: 'extractAfter("abc", "a")',
                expected: '"bc"',
            },
        ],
    },
    {
        name: 'matches',
        category: 'string',
        status: 'unsupported',
        effect: 'pure',
        cases: [
            {
                id: 'matches.digits',
                kind: 'gap',
                input: 'matches("abc", digitsPattern)',
                expected: '0',
            },
        ],
    },
    {
        name: 'wildcardPattern',
        category: 'string',
        status: 'unsupported',
        effect: 'pure',
        cases: [
            {
                id: 'wildcard.m',
                kind: 'gap',
                input: 'wildcardPattern("*.m")',
                expected: '...',
            },
        ],
    },
    {
        name: 'datetime_arith',
        category: 'datetime',
        status: 'unsupported',
        effect: 'pure',
        cases: [
            {
                id: 'datetime.caldays',
                kind: 'gap',
                input: 'datetime(2020, 1, 1) + caldays(1)',
                expected: 'datetime(2020, 1, 2)',
            },
            {
                id: 'datetime.days',
                kind: 'gap',
                input: 'datetime(2020, 1, 1) + days(1)',
                expected: 'datetime(2020, 1, 2)',
            },
        ],
    },
    {
        name: 'caldiff',
        category: 'datetime',
        status: 'unsupported',
        effect: 'pure',
        cases: [
            {
                id: 'caldiff.year',
                kind: 'gap',
                input: 'caldiff(datetime(2020, 1, 1), datetime(2021, 1, 1))',
                expected: '...',
            },
        ],
    },
    {
        name: 'outerjoin',
        category: 'table',
        status: 'unsupported',
        effect: 'pure',
        notes: 'SILENT WRONG: cell {\'k\'} in VariableNames stripped to \'k\'',
        cases: [
            {
                id: 'outerjoin.k',
                kind: 'gap',
                input: "outerjoin(table([1; 2], 'VariableNames', {'k'}), table([2; 3], 'VariableNames', {'k'}))",
                expected: '...',
                notes: "currently VariableNames 'k' without cell",
            },
        ],
    },
    {
        name: 'leftjoin',
        category: 'table',
        status: 'unsupported',
        effect: 'pure',
        notes: 'same cell VariableNames strip as outerjoin',
        cases: [
            {
                id: 'leftjoin.k',
                kind: 'gap',
                input: "leftjoin(table([1; 2], 'VariableNames', {'k'}), table([2; 3], 'VariableNames', {'k'}))",
                expected: '...',
            },
        ],
    },
    {
        name: 'spalloc',
        category: 'matrix',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'spalloc.332', kind: 'gap', input: 'spalloc(3, 3, 2)', expected: '...' }],
    },
    {
        name: 'sparse_ijv',
        category: 'matrix',
        status: 'unsupported',
        effect: 'pure',
        cases: [
            {
                id: 'sparse.ijv',
                kind: 'gap',
                input: 'sparse(1, 2, 3, 4, 4)',
                expected: '...',
            },
        ],
    },
    {
        name: 'full_speye',
        category: 'matrix',
        status: 'unsupported',
        effect: 'pure',
        cases: [
            {
                id: 'full.speye2',
                kind: 'gap',
                input: 'full(speye(2))',
                expected: '[1, 0; 0, 1]',
            },
        ],
    },
    {
        name: 'spones',
        category: 'matrix',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'spones.eye', kind: 'gap', input: 'spones(speye(2))', expected: '...' }],
    },
    {
        name: 'spfun',
        category: 'matrix',
        status: 'unsupported',
        effect: 'pure',
        notes: 'SILENT WRONG: @ stripped — spfun(@sqrt,speye(2)) → spfun(sqrt, speye(2))',
        cases: [
            {
                id: 'spfun.sqrt',
                kind: 'gap',
                input: 'spfun(@sqrt, speye(2))',
                expected: '...',
                notes: 'currently spfun(sqrt, speye(2))',
            },
        ],
    },
    {
        name: 'minres',
        category: 'linear_algebra',
        status: 'unsupported',
        effect: 'pure',
        cases: [
            {
                id: 'minres.eye',
                kind: 'gap',
                input: 'minres(speye(3), ones(3, 1))',
                expected: '...',
            },
        ],
    },
    {
        name: 'cgs',
        category: 'linear_algebra',
        status: 'unsupported',
        effect: 'pure',
        cases: [
            {
                id: 'cgs.eye',
                kind: 'gap',
                input: 'cgs(speye(3), ones(3, 1))',
                expected: '...',
            },
        ],
    },
    {
        name: 'lsqr',
        category: 'linear_algebra',
        status: 'unsupported',
        effect: 'pure',
        cases: [
            {
                id: 'lsqr.eye',
                kind: 'gap',
                input: 'lsqr(speye(3), ones(3, 1))',
                expected: '...',
            },
        ],
    },
    {
        name: 'svd_econ',
        category: 'linear_algebra',
        status: 'unsupported',
        effect: 'pure',
        cases: [
            {
                id: 'svd.econ',
                kind: 'gap',
                input: 'svd(magic(3), "econ")',
                expected: '...',
            },
        ],
    },
    {
        name: 'end_slice',
        category: 'indexing',
        status: 'unsupported',
        effect: 'pure',
        notes: 'D(1:end-1) / E(1:end,end) oak error; C(0) stays C(0)',
        cases: [
            {
                id: 'end.slice_minus',
                kind: 'gap',
                input: 'D=[1, 2, 3]; D(1:end-1)',
                expected: '[1, 2]',
                notes: 'oak error node',
            },
            {
                id: 'end.slice_2d',
                kind: 'gap',
                input: 'E=[1, 2; 3, 4]; E(1:end, end)',
                expected: '[2; 4]',
                notes: 'oak error node',
            },
        ],
    },
    {
        name: 'ginput',
        category: 'plot',
        status: 'planned',
        effect: 'effectful',
        cases: [{ id: 'ginput.basic', kind: 'gap', input: 'ginput', expected: '...' }],
    },
    {
        name: 'zoom',
        category: 'plot',
        status: 'planned',
        effect: 'effectful',
        cases: [{ id: 'zoom.basic', kind: 'gap', input: 'zoom', expected: '...' }],
    },
    {
        name: 'uigridlayout',
        category: 'ui',
        status: 'planned',
        effect: 'effectful',
        cases: [
            {
                id: 'uigridlayout.basic',
                kind: 'gap',
                input: 'uigridlayout',
                expected: '...',
            },
        ],
    },
    {
        name: 'drawnow',
        category: 'ui',
        status: 'planned',
        effect: 'effectful',
        cases: [{ id: 'drawnow.basic', kind: 'gap', input: 'drawnow', expected: '...' }],
    },
    {
        name: 'compose',
        category: 'functional',
        status: 'unsupported',
        effect: 'pure',
        cases: [
            {
                id: 'compose.sincos',
                kind: 'gap',
                input: 'compose(sin, cos, 0)',
                expected: '0',
            },
        ],
    },
] as const satisfies readonly FeatureEntry[];
