import type { FeatureEntry } from './types.js';

/**
 * MATLAB dialect capability matrix.
 *
 * Status is honest against current SXO + Athena behavior.
 */
export const featureMatrix = [
    {
        name: 'plus',
        category: 'arithmetic',
        status: 'supported',
        effect: 'pure',
        cases: [{ id: 'plus.basic', kind: 'eval', input: '2 + 3', expected: '5' }],
    },
    {
        name: 'mtimes',
        category: 'arithmetic',
        status: 'partial',
        effect: 'pure',
        notes: 'scalar * works; matrix mtimes vs times OperatorId split incomplete',
        cases: [{ id: 'mtimes.scalar', kind: 'eval', input: '2 * 3', expected: '6' }],
    },
    {
        name: 'times',
        category: 'arithmetic',
        status: 'partial',
        effect: 'pure',
        notes: '.* often lowers/renders as * without elementwise OperatorId',
        cases: [
            { id: 'times.scalar', kind: 'eval', input: '2.*[1, 2]', expected: '2*[1, 2]' },
            {
                id: 'times.vec',
                kind: 'gap',
                input: '[1, 2].*[3, 4]',
                expected: '[3, 8]',
                notes: 'needs elementwise Times OperatorId + MatrixValue',
            },
        ],
    },
    {
        name: 'power',
        category: 'arithmetic',
        status: 'partial',
        effect: 'pure',
        notes: 'scalar ^ works; .^ does not keep elementwise OperatorId',
        cases: [
            { id: 'power.basic', kind: 'eval', input: '2^3', expected: '8' },
            {
                id: 'power.elementwise',
                kind: 'gap',
                input: '[1, 2].^[2, 3]',
                expected: '[1, 8]',
                notes: 'currently renders as [1, 2]^[2, 3]',
            },
        ],
    },
    {
        name: 'mrdivide',
        category: 'arithmetic',
        status: 'supported',
        effect: 'pure',
        cases: [{ id: 'mrdivide.basic', kind: 'eval', input: '6 / 2', expected: '3' }],
    },
    {
        name: 'rdivide',
        category: 'arithmetic',
        status: 'partial',
        effect: 'pure',
        cases: [{ id: 'rdivide.scalar', kind: 'eval', input: '1./2', expected: '0.5' }],
    },
    {
        name: 'matrix',
        category: 'matrix',
        status: 'partial',
        effect: 'pure',
        notes: 'literal parse/render works; not yet Athena MatrixValue',
        cases: [
            { id: 'matrix.literal', kind: 'eval', input: '[1, 2; 3, 4]', expected: '[1, 2; 3, 4]' },
            { id: 'matrix.roundtrip', kind: 'roundtrip', input: '[1 2; 3 4]', expected: '[1, 2; 3, 4]' },
        ],
    },
    {
        name: 'colon',
        category: 'indexing',
        status: 'partial',
        effect: 'pure',
        notes: '1:3 becomes Span(1, 3), not expanded range vector',
        cases: [
            {
                id: 'colon.range',
                kind: 'gap',
                input: '1:3',
                expected: '[1, 2, 3]',
                notes: 'must not expand at lowering into flat list without Range/Span object',
            },
        ],
    },
    {
        name: 'subsref',
        category: 'indexing',
        status: 'partial',
        effect: 'pure',
        notes: 'scalar 1-based index works; slice (1:2) returns Span not subarray; end oak error',
        cases: [
            { id: 'subsref.vec', kind: 'eval', input: '[1, 2, 3](2)', expected: '2' },
            { id: 'subsref.matrix', kind: 'eval', input: '[1, 2; 3, 4](1, 2)', expected: '2' },
            {
                id: 'subsref.slice',
                kind: 'gap',
                input: '[1, 2, 3](1:2)',
                expected: '[1, 2]',
                notes: 'currently Span(1, 2)',
            },
        ],
    },
    {
        name: 'end',
        category: 'indexing',
        status: 'unsupported',
        effect: 'pure',
        notes: 'oak error node on (end)',
        cases: [{ id: 'end.index', kind: 'gap', input: '[1, 2, 3](end)', expected: '3' }],
    },
    {
        name: 'transpose',
        category: 'matrix',
        status: 'unsupported',
        effect: 'pure',
        notes: "oak rejects ' transpose literal",
        cases: [{ id: 'transpose.vec', kind: 'gap', input: "[1; 2]'", expected: '[1, 2]' }],
    },
    {
        name: 'ctranspose',
        category: 'matrix',
        status: 'unsupported',
        effect: 'pure',
        notes: "depends on complex literal + '",
        cases: [{ id: 'ctranspose.basic', kind: 'gap', input: "[1+1i]'", expected: '1-1i' }],
    },
    {
        name: 'assignment',
        category: 'session',
        status: 'partial',
        effect: 'stateful',
        notes: 'no Session binding persistence',
        cases: [
            {
                id: 'assign.persist',
                kind: 'gap',
                input: 'x = 5; x + 1',
                expected: '6',
                notes: 'currently returns 1 + x',
            },
        ],
    },
    {
        name: 'sequence',
        category: 'session',
        status: 'supported',
        effect: 'pure',
        cases: [{ id: 'seq.last', kind: 'eval', input: '1; 2 + 2', expected: '4' }],
    },
    {
        name: 'if',
        category: 'control',
        status: 'partial',
        effect: 'pure',
        notes: 'surface if/else parses but branch semantics wrong / numeric truthy fragile',
        cases: [
            {
                id: 'if.else',
                kind: 'gap',
                input: 'if 1, 2, else, 3, end',
                expected: '2',
                notes: 'currently returns 3',
            },
        ],
    },
    {
        name: 'for',
        category: 'control',
        status: 'partial',
        effect: 'stateful',
        notes: 'SILENT WRONG: for i=1:3, i, end returns bare i',
        cases: [
            {
                id: 'for.last',
                kind: 'gap',
                input: 'for i=1:3, i, end',
                expected: '3',
                notes: 'currently returns i',
            },
            {
                id: 'for.sum',
                kind: 'gap',
                input: 's=0; for i=1:3, s=s+i; end; s',
                expected: '6',
            },
        ],
    },
    {
        name: 'while',
        category: 'control',
        status: 'partial',
        effect: 'stateful',
        notes: 'SILENT WRONG: while 0, 1, end returns 1',
        cases: [
            {
                id: 'while.false',
                kind: 'gap',
                input: 'while 0, 1, end',
                expected: '',
                notes: 'currently returns 1',
            },
        ],
    },
    {
        name: 'function_handle',
        category: 'function',
        status: 'unsupported',
        effect: 'pure',
        notes: 'oak error on @(x); feval(@sin,0) strips @',
        cases: [
            { id: 'fh.basic', kind: 'gap', input: 'f=@(x)x^2; f(4)', expected: '16' },
            {
                id: 'fh.feval',
                kind: 'gap',
                input: 'feval(@sin, 0)',
                expected: '0',
                notes: 'currently feval(sin, 0)',
            },
        ],
    },
    {
        name: 'eq',
        category: 'comparison',
        status: 'supported',
        effect: 'pure',
        cases: [{ id: 'eq.true', kind: 'eval', input: '3 == 3', expected: '1' }],
    },
    {
        name: 'ne',
        category: 'comparison',
        status: 'supported',
        effect: 'pure',
        cases: [{ id: 'ne.true', kind: 'eval', input: '3 ~= 2', expected: '1' }],
    },
    {
        name: 'le',
        category: 'comparison',
        status: 'supported',
        effect: 'pure',
        cases: [{ id: 'le.true', kind: 'eval', input: '2 <= 3', expected: '1' }],
    },
    {
        name: 'gt',
        category: 'comparison',
        status: 'supported',
        effect: 'pure',
        cases: [{ id: 'gt.true', kind: 'eval', input: '3 > 2', expected: '1' }],
    },
    {
        name: 'sin',
        category: 'elementary',
        status: 'supported',
        effect: 'pure',
        cases: [{ id: 'sin.0', kind: 'eval', input: 'sin(0)', expected: '0' }],
    },
    {
        name: 'cos',
        category: 'elementary',
        status: 'supported',
        effect: 'pure',
        cases: [{ id: 'cos.0', kind: 'eval', input: 'cos(0)', expected: '1' }],
    },
    {
        name: 'sqrt',
        category: 'elementary',
        status: 'supported',
        effect: 'pure',
        cases: [{ id: 'sqrt.4', kind: 'eval', input: 'sqrt(4)', expected: '2' }],
    },
    {
        name: 'abs',
        category: 'elementary',
        status: 'supported',
        effect: 'pure',
        cases: [{ id: 'abs.neg', kind: 'eval', input: 'abs(-3)', expected: '3' }],
    },
    {
        name: 'exp',
        category: 'elementary',
        status: 'supported',
        effect: 'pure',
        cases: [{ id: 'exp.0', kind: 'eval', input: 'exp(0)', expected: '1' }],
    },
    {
        name: 'log',
        category: 'elementary',
        status: 'supported',
        effect: 'pure',
        cases: [{ id: 'log.1', kind: 'eval', input: 'log(1)', expected: '0' }],
    },
    {
        name: 'listable_sin',
        category: 'elementary',
        status: 'partial',
        effect: 'pure',
        notes: 'sin on vector left as sin([...])',
        cases: [
            {
                id: 'sin.listable',
                kind: 'gap',
                input: 'sin([0, pi/2])',
                expected: '[0, 1]',
            },
        ],
    },
    {
        name: 'simplify',
        category: 'simplify',
        status: 'supported',
        effect: 'pure',
        cases: [
            {
                id: 'simplify.trig',
                kind: 'eval',
                input: 'sin(x)^2 + cos(x)^2',
                expected: '1',
            },
        ],
    },
    {
        name: 'diff',
        category: 'calculus',
        status: 'partial',
        effect: 'pure',
        notes: 'first derivative works; higher-order diff(f,x,2) unevaluated',
        cases: [
            { id: 'diff.poly', kind: 'eval', input: 'diff(x^3, x)', expected: '3*x^2' },
            { id: 'diff.sin', kind: 'eval', input: 'diff(sin(x), x)', expected: 'cos(x)' },
            {
                id: 'diff.order2',
                kind: 'gap',
                input: 'diff(x^2, x, 2)',
                expected: '2',
            },
        ],
    },
    {
        name: 'int',
        category: 'calculus',
        status: 'supported',
        effect: 'pure',
        cases: [
            { id: 'int.poly', kind: 'eval', input: 'int(x^2, x)', expected: '1/3*x^3' },
            { id: 'int.sin', kind: 'eval', input: 'int(sin(x), x)', expected: '-cos(x)' },
        ],
    },
    {
        name: 'solve',
        category: 'solve',
        status: 'planned',
        effect: 'pure',
        notes: 'must lower to Athena SolveGoal',
        cases: [{ id: 'solve.linear', kind: 'gap', input: 'solve(x-1==0, x)', expected: '1' }],
    },
    {
        name: 'mldivide',
        category: 'solve',
        status: 'partial',
        effect: 'pure',
        notes: 'SILENT WRONG: A\\b becomes A^-1*b text',
        cases: [
            {
                id: 'mldivide.2x2',
                kind: 'gap',
                input: '[1,2;3,4] \\ [5;6]',
                expected: '[-4; 4.5]',
                notes: 'currently [1, 2; 3, 4]^-1*[5; 6]',
            },
        ],
    },
    {
        name: 'roots',
        category: 'solve',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'roots.quad', kind: 'gap', input: 'roots([1, 0, -1])', expected: '[1; -1]' }],
    },
    {
        name: 'det',
        category: 'linear_algebra',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'det.2x2', kind: 'gap', input: 'det([1, 2; 3, 4])', expected: '-2' }],
    },
    {
        name: 'inv',
        category: 'linear_algebra',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'inv.diag', kind: 'gap', input: 'inv([1, 0; 0, 2])', expected: '[1, 0; 0, 0.5]' }],
    },
    {
        name: 'rank',
        category: 'linear_algebra',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'rank.def', kind: 'gap', input: 'rank([1, 2; 2, 4])', expected: '1' }],
    },
    {
        name: 'eig',
        category: 'linear_algebra',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'eig.sym', kind: 'gap', input: 'eig([1, 2; 2, 1])', expected: '[3; -1]' }],
    },
    {
        name: 'eye',
        category: 'matrix',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'eye.2', kind: 'gap', input: 'eye(2)', expected: '[1, 0; 0, 1]' }],
    },
    {
        name: 'zeros',
        category: 'matrix',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'zeros.23', kind: 'gap', input: 'zeros(2, 3)', expected: '[0, 0, 0; 0, 0, 0]' }],
    },
    {
        name: 'ones',
        category: 'matrix',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'ones.2', kind: 'gap', input: 'ones(2)', expected: '[1, 1; 1, 1]' }],
    },
    {
        name: 'size',
        category: 'matrix',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'size.2x2', kind: 'gap', input: 'size([1, 2; 3, 4])', expected: '[2, 2]' }],
    },
    {
        name: 'length',
        category: 'matrix',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'length.vec', kind: 'gap', input: 'length([1, 2, 3])', expected: '3' }],
    },
    {
        name: 'sum',
        category: 'matrix',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'sum.vec', kind: 'gap', input: 'sum([1, 2, 3])', expected: '6' }],
    },
    {
        name: 'max',
        category: 'matrix',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'max.vec', kind: 'gap', input: 'max([1, 3, 2])', expected: '3' }],
    },
    {
        name: 'plot',
        category: 'plot',
        status: 'partial',
        effect: 'effectful',
        notes:
            'SVG→PNG visual: curve+L-axes readable; missing tick labels, no boxed frame, not MATLAB default blue. Negative a/b extract fails; 2-arg plot(f,[a,b]) gap',
        cases: [
            {
                id: 'plot.square',
                kind: 'plot',
                input: 'plot(x^2, x, 0, 1)',
                expected: '<svg',
            },
            {
                id: 'plot.sin',
                kind: 'plot',
                input: 'plot(sin(x), x, 0, 6)',
                expected: '<svg',
            },
            {
                id: 'plot.neg_domain',
                kind: 'gap',
                input: 'plot(x^2, x, -1, 1)',
                expected: '<svg',
                notes: 'negative domain bounds fail plot extract',
            },
            {
                id: 'plot.range_vec',
                kind: 'gap',
                input: 'plot(sin(x), [-pi, pi])',
                expected: '<svg',
                notes: 'surface sugar for domain vector',
            },
        ],
    },
    {
        name: 'mesh',
        category: 'plot',
        status: 'unsupported',
        effect: 'effectful',
        cases: [{ id: 'mesh.peaks', kind: 'gap', input: 'mesh(peaks)', expected: '<svg' }],
    },
    {
        name: 'complex',
        category: 'numeric',
        status: 'unsupported',
        effect: 'pure',
        notes: 'oak bad literal on 2i',
        cases: [
            { id: 'complex.i', kind: 'gap', input: '1+2i', expected: '1+2i' },
            { id: 'complex.real', kind: 'gap', input: 'real(1+2i)', expected: '1' },
        ],
    },
    {
        name: 'pi',
        category: 'constant',
        status: 'partial',
        effect: 'pure',
        cases: [{ id: 'pi.symbol', kind: 'eval', input: 'pi', expected: 'pi' }],
    },
    {
        name: 'true',
        category: 'constant',
        status: 'partial',
        effect: 'pure',
        cases: [{ id: 'true.atom', kind: 'eval', input: 'true', expected: 'true' }],
    },
    {
        name: 'false',
        category: 'constant',
        status: 'partial',
        effect: 'pure',
        cases: [{ id: 'false.atom', kind: 'eval', input: 'false', expected: 'false' }],
    },
    {
        name: 'disp',
        category: 'io',
        status: 'unsupported',
        effect: 'effectful',
        cases: [{ id: 'disp.1', kind: 'gap', input: 'disp(1)', expected: '1' }],
    },
] as const satisfies readonly FeatureEntry[];
