import type { FeatureEntry } from './types.js';

/**
 * Mathematica dialect capability matrix.
 *
 * Status is honest against current SXO + Athena behavior.
 * `gap` cases track contract items for upstream handoff.
 */
export const featureMatrix = [
    {
        name: 'Plus',
        category: 'arithmetic',
        status: 'supported',
        effect: 'pure',
        cases: [
            { id: 'plus.basic', kind: 'eval', input: '1 + 2 * 3', expected: '7' },
            { id: 'plus.nary', kind: 'eval', input: 'Plus[1, 2, 3]', expected: '6' },
        ],
    },
    {
        name: 'Times',
        category: 'arithmetic',
        status: 'supported',
        effect: 'pure',
        cases: [{ id: 'times.nary', kind: 'eval', input: 'Times[2, 3, 4]', expected: '24' }],
    },
    {
        name: 'Power',
        category: 'arithmetic',
        status: 'supported',
        effect: 'pure',
        cases: [
            { id: 'power.pow1', kind: 'eval', input: 'Power[x, 1]', expected: 'x' },
            { id: 'power.square', kind: 'eval', input: '2^3', expected: '8' },
        ],
    },
    {
        name: 'Subtract',
        category: 'arithmetic',
        status: 'supported',
        effect: 'pure',
        cases: [{ id: 'subtract.basic', kind: 'eval', input: 'Subtract[5, 2]', expected: '3' }],
    },
    {
        name: 'Divide',
        category: 'arithmetic',
        status: 'supported',
        effect: 'pure',
        cases: [
            { id: 'divide.basic', kind: 'eval', input: 'Divide[6, 2]', expected: '3' },
            { id: 'divide.rational', kind: 'eval', input: '1/3 + 1/3 + 1/3', expected: '1' },
        ],
    },
    {
        name: 'Factorial',
        category: 'arithmetic',
        status: 'supported',
        effect: 'pure',
        cases: [{ id: 'factorial.5', kind: 'eval', input: '5!', expected: '120' }],
    },
    {
        name: 'Sqrt',
        category: 'arithmetic',
        status: 'supported',
        effect: 'pure',
        cases: [{ id: 'sqrt.4', kind: 'eval', input: 'Sqrt[4]', expected: '2' }],
    },
    {
        name: 'Abs',
        category: 'arithmetic',
        status: 'supported',
        effect: 'pure',
        cases: [{ id: 'abs.neg', kind: 'eval', input: 'Abs[-3]', expected: '3' }],
    },
    {
        name: 'Equal',
        category: 'comparison',
        status: 'supported',
        effect: 'pure',
        cases: [{ id: 'equal.true', kind: 'eval', input: '2 == 2', expected: '1' }],
    },
    {
        name: 'Unequal',
        category: 'comparison',
        status: 'supported',
        effect: 'pure',
        cases: [{ id: 'unequal.true', kind: 'eval', input: '2 != 3', expected: '1' }],
    },
    {
        name: 'Less',
        category: 'comparison',
        status: 'supported',
        effect: 'pure',
        cases: [
            { id: 'less.infix', kind: 'eval', input: '2 < 3', expected: '1' },
            { id: 'less.head', kind: 'eval', input: 'Less[2, 3]', expected: '1' },
        ],
    },
    {
        name: 'Greater',
        category: 'comparison',
        status: 'supported',
        effect: 'pure',
        cases: [{ id: 'greater.infix', kind: 'eval', input: '3 > 2', expected: '1' }],
    },
    {
        name: 'LessEqual',
        category: 'comparison',
        status: 'supported',
        effect: 'pure',
        cases: [{ id: 'le.infix', kind: 'eval', input: '2 <= 3', expected: '1' }],
    },
    {
        name: 'GreaterEqual',
        category: 'comparison',
        status: 'supported',
        effect: 'pure',
        cases: [{ id: 'ge.infix', kind: 'eval', input: '3 >= 2', expected: '1' }],
    },
    {
        name: 'And',
        category: 'logic',
        status: 'partial',
        effect: 'pure',
        notes: 'True/False symbols parse incorrectly; And[True,False] collapses',
        cases: [
            {
                id: 'and.head',
                kind: 'gap',
                input: 'And[True, False]',
                expected: '0',
                notes: 'needs Boolean atoms + And short-circuit',
            },
        ],
    },
    {
        name: 'Or',
        category: 'logic',
        status: 'partial',
        effect: 'pure',
        notes: 'same Boolean atom gap as And',
        cases: [{ id: 'or.head', kind: 'gap', input: 'Or[False, True]', expected: '1' }],
    },
    {
        name: 'Not',
        category: 'logic',
        status: 'partial',
        effect: 'pure',
        notes: 'Not[True] currently renders Not[]',
        cases: [{ id: 'not.true', kind: 'gap', input: 'Not[True]', expected: '0' }],
    },
    {
        name: 'If',
        category: 'logic',
        status: 'partial',
        effect: 'pure',
        notes: 'If is not a real conditional; args evaluate incorrectly',
        cases: [
            {
                id: 'if.true',
                kind: 'gap',
                input: 'If[1 == 1, 7, 8]',
                expected: '7',
                notes: 'currently returns 8',
            },
        ],
    },
    {
        name: 'Which',
        category: 'logic',
        status: 'unsupported',
        effect: 'pure',
        cases: [
            {
                id: 'which.basic',
                kind: 'gap',
                input: 'Which[False, 1, True, 2]',
                expected: '2',
            },
        ],
    },
    {
        name: 'List',
        category: 'list',
        status: 'supported',
        effect: 'pure',
        cases: [
            { id: 'list.literal', kind: 'eval', input: '{1, 2, 3}', expected: '{1, 2, 3}' },
            { id: 'list.roundtrip', kind: 'roundtrip', input: '{1, 2}', expected: '{1, 2}' },
        ],
    },
    {
        name: 'Part',
        category: 'list',
        status: 'supported',
        effect: 'pure',
        notes: '1-based Part on lists',
        cases: [
            { id: 'part.infix', kind: 'eval', input: '{1, 2, 3}[[2]]', expected: '2' },
            { id: 'part.head', kind: 'eval', input: 'Part[{1, 2, 3}, 1]', expected: '1' },
        ],
    },
    {
        name: 'Range',
        category: 'list',
        status: 'unsupported',
        effect: 'pure',
        notes: 'Range[3] left unevaluated',
        cases: [{ id: 'range.3', kind: 'gap', input: 'Range[3]', expected: '{1, 2, 3}' }],
    },
    {
        name: 'Map',
        category: 'list',
        status: 'partial',
        effect: 'pure',
        notes: 'Map[Sin,{0,1}] works; pure-function Map broken',
        cases: [
            { id: 'map.sin', kind: 'eval', input: 'Map[Sin, {0, 1}]', expected: '{0, 1}' },
            {
                id: 'map.slot',
                kind: 'gap',
                input: 'Map[#^2 &, {1, 2, 3}]',
                expected: '{1, 4, 9}',
            },
        ],
    },
    {
        name: 'CompoundExpression',
        category: 'session',
        status: 'partial',
        effect: 'pure',
        notes: 'returns last value; no persistent Set side effects',
        cases: [{ id: 'compound.last', kind: 'eval', input: '1 + 2; 3 * 4', expected: '12' }],
    },
    {
        name: 'Set',
        category: 'session',
        status: 'partial',
        effect: 'stateful',
        notes: 'RHS eval only; no Session binding',
        cases: [
            {
                id: 'set.persist',
                kind: 'gap',
                input: 'x = 5; x + 1',
                expected: '6',
                notes: 'currently returns 1 + x',
            },
        ],
    },
    {
        name: 'SetDelayed',
        category: 'session',
        status: 'planned',
        effect: 'stateful',
        notes: 'must lower to Stmt/Definition',
        cases: [{ id: 'setdelayed.def', kind: 'gap', input: 'f[x_] := x^2; f[3]', expected: '9' }],
    },
    {
        name: 'Function',
        category: 'function',
        status: 'partial',
        effect: 'pure',
        notes: 'Slot/#& application broken or identity-like',
        cases: [
            {
                id: 'function.slot',
                kind: 'gap',
                input: '(#^2)&[4]',
                expected: '16',
                notes: 'currently returns 4',
            },
            {
                id: 'function.named',
                kind: 'gap',
                input: 'Function[x, x^2][3]',
                expected: '9',
            },
        ],
    },
    {
        name: 'Rule',
        category: 'rule',
        status: 'partial',
        effect: 'pure',
        notes: 'Rule parse/render fragile; ReplaceAll broken',
        cases: [
            {
                id: 'rule.replaceall',
                kind: 'gap',
                input: 'ReplaceAll[x^2, Rule[x, 3]]',
                expected: '9',
            },
        ],
    },
    {
        name: 'RuleDelayed',
        category: 'rule',
        status: 'planned',
        effect: 'pure',
        cases: [{ id: 'ruledelayed.basic', kind: 'gap', input: 'x /. x :> 1 + 1', expected: '2' }],
    },
    {
        name: 'Replace',
        category: 'rule',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'replace.basic', kind: 'gap', input: 'Replace[a, a -> 1]', expected: '1' }],
    },
    {
        name: 'ReplaceAll',
        category: 'rule',
        status: 'unsupported',
        effect: 'pure',
        notes: 'infix /. often oak error',
        cases: [{ id: 'replaceall.infix', kind: 'gap', input: 'x^2 /. x -> 3', expected: '9' }],
    },
    {
        name: 'Hold',
        category: 'hold',
        status: 'partial',
        effect: 'unevaluated',
        notes: 'Hold does not prevent evaluation of arguments',
        cases: [
            {
                id: 'hold.plus',
                kind: 'gap',
                input: 'Hold[1 + 1]',
                expected: 'Hold[1 + 1]',
                notes: 'currently Hold[2]',
            },
        ],
    },
    {
        name: 'HoldForm',
        category: 'hold',
        status: 'partial',
        effect: 'unevaluated',
        cases: [
            {
                id: 'holdform.plus',
                kind: 'gap',
                input: 'HoldForm[1 + 1]',
                expected: 'HoldForm[1 + 1]',
            },
        ],
    },
    {
        name: 'HoldAll',
        category: 'attributes',
        status: 'planned',
        effect: 'unevaluated',
        cases: [{ id: 'attr.holdall', kind: 'gap', input: 'Attributes[Hold]', expected: '{HoldAll}' }],
    },
    {
        name: 'Listable',
        category: 'attributes',
        status: 'planned',
        effect: 'pure',
        cases: [{ id: 'attr.listable', kind: 'gap', input: 'Sin[{0, Pi}]', expected: '{0, 0}' }],
    },
    {
        name: 'Orderless',
        category: 'attributes',
        status: 'planned',
        effect: 'pure',
        cases: [{ id: 'attr.orderless', kind: 'gap', input: 'Plus[b, a]', expected: 'a + b' }],
    },
    {
        name: 'Sin',
        category: 'elementary',
        status: 'supported',
        effect: 'pure',
        cases: [{ id: 'sin.0', kind: 'eval', input: 'Sin[0]', expected: '0' }],
    },
    {
        name: 'Cos',
        category: 'elementary',
        status: 'supported',
        effect: 'pure',
        cases: [{ id: 'cos.0', kind: 'eval', input: 'Cos[0]', expected: '1' }],
    },
    {
        name: 'Tan',
        category: 'elementary',
        status: 'supported',
        effect: 'pure',
        cases: [{ id: 'tan.0', kind: 'eval', input: 'Tan[0]', expected: '0' }],
    },
    {
        name: 'Exp',
        category: 'elementary',
        status: 'supported',
        effect: 'pure',
        cases: [{ id: 'exp.0', kind: 'eval', input: 'Exp[0]', expected: '1' }],
    },
    {
        name: 'Log',
        category: 'elementary',
        status: 'supported',
        effect: 'pure',
        cases: [{ id: 'log.1', kind: 'eval', input: 'Log[1]', expected: '0' }],
    },
    {
        name: 'Simplify',
        category: 'simplify',
        status: 'supported',
        effect: 'pure',
        cases: [
            {
                id: 'simplify.trig',
                kind: 'eval',
                input: 'Simplify[Sin[x]^2 + Cos[x]^2]',
                expected: '1',
            },
        ],
    },
    {
        name: 'D',
        category: 'calculus',
        status: 'supported',
        effect: 'pure',
        cases: [{ id: 'd.poly', kind: 'eval', input: 'D[x^3, x]', expected: '3*x^2' }],
    },
    {
        name: 'Integrate',
        category: 'calculus',
        status: 'supported',
        effect: 'pure',
        cases: [{ id: 'integrate.poly', kind: 'eval', input: 'Integrate[x^2, x]', expected: '1/3*x^3' }],
    },
    {
        name: 'Limit',
        category: 'calculus',
        status: 'planned',
        effect: 'pure',
        cases: [{ id: 'limit.basic', kind: 'gap', input: 'Limit[Sin[x]/x, x -> 0]', expected: '1' }],
    },
    {
        name: 'Series',
        category: 'calculus',
        status: 'planned',
        effect: 'pure',
        cases: [
            {
                id: 'series.basic',
                kind: 'gap',
                input: 'Series[Exp[x], {x, 0, 2}]',
                expected: '1 + x + x^2/2',
            },
        ],
    },
    {
        name: 'Solve',
        category: 'solve',
        status: 'planned',
        effect: 'pure',
        notes: 'must lower to Athena SolveGoal',
        cases: [
            {
                id: 'solve.quad',
                kind: 'gap',
                input: 'Solve[x^2 == 1, x]',
                expected: '{{x -> -1}, {x -> 1}}',
            },
        ],
    },
    {
        name: 'NSolve',
        category: 'solve',
        status: 'planned',
        effect: 'pure',
        cases: [{ id: 'nsolve.quad', kind: 'gap', input: 'NSolve[x^2 == 1, x]', expected: '{{x -> -1.}, {x -> 1.}}' }],
    },
    {
        name: 'DSolve',
        category: 'solve',
        status: 'planned',
        effect: 'pure',
        cases: [
            {
                id: 'dsolve.basic',
                kind: 'gap',
                input: 'DSolve[y\'[x] == y[x], y[x], x]',
                expected: '{{y[x] -> E^x C[1]}}',
            },
        ],
    },
    {
        name: 'Plot',
        category: 'plot',
        status: 'partial',
        effect: 'effectful',
        notes:
            'SVG→PNG visual: curve+L-axes readable; missing tick labels, no Frame, not commercial MMA axes-at-origin. Negative domain {x,-1,1} extract fails',
        cases: [
            {
                id: 'plot.square',
                kind: 'plot',
                input: 'Plot[x^2, {x, 0, 1}]',
                expected: '<svg',
            },
            {
                id: 'plot.sin',
                kind: 'plot',
                input: 'Plot[Sin[x], {x, 0, 6}]',
                expected: '<svg',
            },
            {
                id: 'plot.neg_domain',
                kind: 'gap',
                input: 'Plot[x^2, {x, -1, 1}]',
                expected: '<svg',
                notes: 'unary minus in iterator breaks plot extract',
            },
        ],
    },
    {
        name: 'ExactInteger',
        category: 'numeric',
        status: 'supported',
        effect: 'pure',
        cases: [
            {
                id: 'bigint.add',
                kind: 'eval',
                input: '99999999999999999999 + 1',
                expected: '100000000000000000000',
            },
        ],
    },
] as const satisfies readonly FeatureEntry[];
