import type { FeatureEntry } from './types.js';

/**
 * Mathematica dialect capability matrix.
 *
 * Status is honest against current SXO + Athena behavior.
 * `gap` cases track contract items for upstream handoff.
 */
export const featureMatrix = [
    {
        name: 'Plus',
        category: 'arithmetic',
        status: 'supported',
        effect: 'pure',
        cases: [
            { id: 'plus.basic', kind: 'eval', input: '1 + 2 * 3', expected: '7' },
            { id: 'plus.nary', kind: 'eval', input: 'Plus[1, 2, 3]', expected: '6' },
        ],
    },
    {
        name: 'Times',
        category: 'arithmetic',
        status: 'supported',
        effect: 'pure',
        cases: [{ id: 'times.nary', kind: 'eval', input: 'Times[2, 3, 4]', expected: '24' }],
    },
    {
        name: 'Power',
        category: 'arithmetic',
        status: 'supported',
        effect: 'pure',
        cases: [
            { id: 'power.pow1', kind: 'eval', input: 'Power[x, 1]', expected: 'x' },
            { id: 'power.square', kind: 'eval', input: '2^3', expected: '8' },
        ],
    },
    {
        name: 'Subtract',
        category: 'arithmetic',
        status: 'supported',
        effect: 'pure',
        cases: [{ id: 'subtract.basic', kind: 'eval', input: 'Subtract[5, 2]', expected: '3' }],
    },
    {
        name: 'Divide',
        category: 'arithmetic',
        status: 'supported',
        effect: 'pure',
        cases: [
            { id: 'divide.basic', kind: 'eval', input: 'Divide[6, 2]', expected: '3' },
            { id: 'divide.rational', kind: 'eval', input: '1/3 + 1/3 + 1/3', expected: '1' },
        ],
    },
    {
        name: 'Factorial',
        category: 'arithmetic',
        status: 'supported',
        effect: 'pure',
        cases: [{ id: 'factorial.5', kind: 'eval', input: '5!', expected: '120' }],
    },
    {
        name: 'Sqrt',
        category: 'arithmetic',
        status: 'supported',
        effect: 'pure',
        cases: [{ id: 'sqrt.4', kind: 'eval', input: 'Sqrt[4]', expected: '2' }],
    },
    {
        name: 'Abs',
        category: 'arithmetic',
        status: 'supported',
        effect: 'pure',
        cases: [{ id: 'abs.neg', kind: 'eval', input: 'Abs[-3]', expected: '3' }],
    },
    {
        name: 'Equal',
        category: 'comparison',
        status: 'supported',
        effect: 'pure',
        cases: [{ id: 'equal.true', kind: 'eval', input: '2 == 2', expected: '1' }],
    },
    {
        name: 'Unequal',
        category: 'comparison',
        status: 'supported',
        effect: 'pure',
        cases: [{ id: 'unequal.true', kind: 'eval', input: '2 != 3', expected: '1' }],
    },
    {
        name: 'Less',
        category: 'comparison',
        status: 'supported',
        effect: 'pure',
        cases: [
            { id: 'less.infix', kind: 'eval', input: '2 < 3', expected: '1' },
            { id: 'less.head', kind: 'eval', input: 'Less[2, 3]', expected: '1' },
        ],
    },
    {
        name: 'Greater',
        category: 'comparison',
        status: 'supported',
        effect: 'pure',
        cases: [{ id: 'greater.infix', kind: 'eval', input: '3 > 2', expected: '1' }],
    },
    {
        name: 'LessEqual',
        category: 'comparison',
        status: 'supported',
        effect: 'pure',
        cases: [{ id: 'le.infix', kind: 'eval', input: '2 <= 3', expected: '1' }],
    },
    {
        name: 'GreaterEqual',
        category: 'comparison',
        status: 'supported',
        effect: 'pure',
        cases: [{ id: 'ge.infix', kind: 'eval', input: '3 >= 2', expected: '1' }],
    },
    {
        name: 'And',
        category: 'logic',
        status: 'partial',
        effect: 'pure',
        notes: 'And over Equal works as 0/1; True/False atoms parse empty and break And[True,…]',
        cases: [
            { id: 'and.equal', kind: 'eval', input: 'And[1 == 1, 2 == 2]', expected: '1' },
            {
                id: 'and.bool_atoms',
                kind: 'gap',
                input: 'And[True, False]',
                expected: 'False',
                notes: 'needs Boolean atoms',
            },
        ],
    },
    {
        name: 'Or',
        category: 'logic',
        status: 'partial',
        effect: 'pure',
        notes: 'Or over Equal works; True/False atoms broken',
        cases: [
            { id: 'or.equal', kind: 'eval', input: 'Or[1 == 2, 2 == 2]', expected: '1' },
            { id: 'or.bool_atoms', kind: 'gap', input: 'Or[False, True]', expected: 'True' },
        ],
    },
    {
        name: 'Not',
        category: 'logic',
        status: 'partial',
        effect: 'pure',
        notes: 'Not over Equal works; Not[True] collapses',
        cases: [
            { id: 'not.equal', kind: 'eval', input: 'Not[1 == 2]', expected: '1' },
            { id: 'not.true', kind: 'gap', input: 'Not[True]', expected: 'False' },
        ],
    },
    {
        name: 'If',
        category: 'logic',
        status: 'partial',
        effect: 'pure',
        notes: 'If is not a real conditional; args evaluate incorrectly',
        cases: [
            {
                id: 'if.true',
                kind: 'gap',
                input: 'If[1 == 1, 7, 8]',
                expected: '7',
                notes: 'currently returns 8',
            },
        ],
    },
    {
        name: 'Which',
        category: 'logic',
        status: 'unsupported',
        effect: 'pure',
        cases: [
            {
                id: 'which.basic',
                kind: 'gap',
                input: 'Which[False, 1, True, 2]',
                expected: '2',
            },
        ],
    },
    {
        name: 'List',
        category: 'list',
        status: 'supported',
        effect: 'pure',
        cases: [
            { id: 'list.literal', kind: 'eval', input: '{1, 2, 3}', expected: '{1, 2, 3}' },
            { id: 'list.roundtrip', kind: 'roundtrip', input: '{1, 2}', expected: '{1, 2}' },
        ],
    },
    {
        name: 'Part',
        category: 'list',
        status: 'partial',
        effect: 'pure',
        notes: '1-based Part works; [[0]] silently returns 0 (wrong)',
        cases: [
            { id: 'part.infix', kind: 'eval', input: '{1, 2, 3}[[2]]', expected: '2' },
            { id: 'part.head', kind: 'eval', input: 'Part[{1, 2, 3}, 1]', expected: '1' },
            {
                id: 'part.zero',
                kind: 'gap',
                input: '{1, 2, 3}[[0]]',
                expected: 'List',
                notes: 'currently returns 0',
            },
        ],
    },
    {
        name: 'Range',
        category: 'list',
        status: 'unsupported',
        effect: 'pure',
        notes: 'Range[3] left unevaluated',
        cases: [{ id: 'range.3', kind: 'gap', input: 'Range[3]', expected: '{1, 2, 3}' }],
    },
    {
        name: 'Map',
        category: 'list',
        status: 'partial',
        effect: 'pure',
        notes: 'Map[Sin,{0,1}] works; pure-function Map broken',
        cases: [
            { id: 'map.sin', kind: 'eval', input: 'Map[Sin, {0, 1}]', expected: '{0, 1}' },
            {
                id: 'map.slot',
                kind: 'gap',
                input: 'Map[#^2 &, {1, 2, 3}]',
                expected: '{1, 4, 9}',
            },
        ],
    },
    {
        name: 'CompoundExpression',
        category: 'session',
        status: 'partial',
        effect: 'pure',
        notes: 'returns last value; no persistent Set side effects',
        cases: [{ id: 'compound.last', kind: 'eval', input: '1 + 2; 3 * 4', expected: '12' }],
    },
    {
        name: 'Set',
        category: 'session',
        status: 'partial',
        effect: 'stateful',
        notes: 'RHS eval only; no Session binding',
        cases: [
            {
                id: 'set.persist',
                kind: 'gap',
                input: 'x = 5; x + 1',
                expected: '6',
                notes: 'currently returns 1 + x',
            },
        ],
    },
    {
        name: 'SetDelayed',
        category: 'session',
        status: 'planned',
        effect: 'stateful',
        notes: 'must lower to Stmt/Definition',
        cases: [{ id: 'setdelayed.def', kind: 'gap', input: 'f[x_] := x^2; f[3]', expected: '9' }],
    },
    {
        name: 'Function',
        category: 'function',
        status: 'partial',
        effect: 'pure',
        notes: 'Slot/#& application broken or identity-like',
        cases: [
            {
                id: 'function.slot',
                kind: 'gap',
                input: '(#^2)&[4]',
                expected: '16',
                notes: 'currently returns 4',
            },
            {
                id: 'function.named',
                kind: 'gap',
                input: 'Function[x, x^2][3]',
                expected: '9',
            },
        ],
    },
    {
        name: 'Rule',
        category: 'rule',
        status: 'partial',
        effect: 'pure',
        notes: 'head ReplaceAll[expr, lhs->rhs] works for simple symbols; RuleDelayed / infix /. fragile',
        cases: [
            { id: 'rule.replaceall_pow', kind: 'eval', input: 'ReplaceAll[x^2, x -> 3]', expected: '9' },
            {
                id: 'rule.replaceall_named',
                kind: 'gap',
                input: 'ReplaceAll[x^2, Rule[x, 3]]',
                expected: '9',
                notes: 'Rule[…] may flatten args',
            },
        ],
    },
    {
        name: 'RuleDelayed',
        category: 'rule',
        status: 'planned',
        effect: 'pure',
        cases: [{ id: 'ruledelayed.basic', kind: 'gap', input: 'x /. x :> 1 + 1', expected: '2' }],
    },
    {
        name: 'Replace',
        category: 'rule',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'replace.basic', kind: 'gap', input: 'Replace[a, a -> 1]', expected: '1' }],
    },
    {
        name: 'ReplaceAll',
        category: 'rule',
        status: 'partial',
        effect: 'pure',
        notes: 'head form works; infix /. often oak error',
        cases: [
            { id: 'replaceall.head', kind: 'eval', input: 'ReplaceAll[x, x -> 3]', expected: '3' },
            { id: 'replaceall.infix', kind: 'gap', input: 'x^2 /. x -> 3', expected: '9' },
        ],
    },
    {
        name: 'Hold',
        category: 'hold',
        status: 'partial',
        effect: 'unevaluated',
        notes: 'Hold does not prevent evaluation of arguments',
        cases: [
            {
                id: 'hold.plus',
                kind: 'gap',
                input: 'Hold[1 + 1]',
                expected: 'Hold[1 + 1]',
                notes: 'currently Hold[2]',
            },
        ],
    },
    {
        name: 'HoldForm',
        category: 'hold',
        status: 'partial',
        effect: 'unevaluated',
        cases: [
            {
                id: 'holdform.plus',
                kind: 'gap',
                input: 'HoldForm[1 + 1]',
                expected: 'HoldForm[1 + 1]',
            },
        ],
    },
    {
        name: 'HoldAll',
        category: 'attributes',
        status: 'planned',
        effect: 'unevaluated',
        cases: [{ id: 'attr.holdall', kind: 'gap', input: 'Attributes[Hold]', expected: '{HoldAll}' }],
    },
    {
        name: 'Listable',
        category: 'attributes',
        status: 'planned',
        effect: 'pure',
        cases: [{ id: 'attr.listable', kind: 'gap', input: 'Sin[{0, Pi}]', expected: '{0, 0}' }],
    },
    {
        name: 'Orderless',
        category: 'attributes',
        status: 'planned',
        effect: 'pure',
        cases: [{ id: 'attr.orderless', kind: 'gap', input: 'Plus[b, a]', expected: 'a + b' }],
    },
    {
        name: 'Sin',
        category: 'elementary',
        status: 'supported',
        effect: 'pure',
        cases: [{ id: 'sin.0', kind: 'eval', input: 'Sin[0]', expected: '0' }],
    },
    {
        name: 'Cos',
        category: 'elementary',
        status: 'supported',
        effect: 'pure',
        cases: [{ id: 'cos.0', kind: 'eval', input: 'Cos[0]', expected: '1' }],
    },
    {
        name: 'Tan',
        category: 'elementary',
        status: 'supported',
        effect: 'pure',
        cases: [{ id: 'tan.0', kind: 'eval', input: 'Tan[0]', expected: '0' }],
    },
    {
        name: 'Exp',
        category: 'elementary',
        status: 'supported',
        effect: 'pure',
        cases: [{ id: 'exp.0', kind: 'eval', input: 'Exp[0]', expected: '1' }],
    },
    {
        name: 'Log',
        category: 'elementary',
        status: 'supported',
        effect: 'pure',
        cases: [{ id: 'log.1', kind: 'eval', input: 'Log[1]', expected: '0' }],
    },
    {
        name: 'Simplify',
        category: 'simplify',
        status: 'supported',
        effect: 'pure',
        cases: [
            {
                id: 'simplify.trig',
                kind: 'eval',
                input: 'Simplify[Sin[x]^2 + Cos[x]^2]',
                expected: '1',
            },
        ],
    },
    {
        name: 'D',
        category: 'calculus',
        status: 'supported',
        effect: 'pure',
        cases: [
            { id: 'd.poly', kind: 'eval', input: 'D[x^3, x]', expected: '3*x^2' },
            { id: 'd.sin2', kind: 'eval', input: 'D[Sin[x], {x, 2}]', expected: '-Sin[x]' },
        ],
    },
    {
        name: 'Integrate',
        category: 'calculus',
        status: 'partial',
        effect: 'pure',
        notes: 'indefinite poly works; definite Integrate[Sin[x],{x,0,Pi}] returns 1+-Cos[Pi] not 2',
        cases: [
            { id: 'integrate.poly', kind: 'eval', input: 'Integrate[x^2, x]', expected: '1/3*x^3' },
            {
                id: 'integrate.definite_sin',
                kind: 'gap',
                input: 'Integrate[Sin[x], {x, 0, Pi}]',
                expected: '2',
                notes: 'currently 1 + -Cos[Pi]',
            },
        ],
    },
    {
        name: 'Limit',
        category: 'calculus',
        status: 'partial',
        effect: 'pure',
        notes: 'SILENT WRONG: Limit[Sin[x]/x,x->0] returns 0 (should be 1)',
        cases: [
            {
                id: 'limit.sinc',
                kind: 'gap',
                input: 'Limit[Sin[x]/x, x -> 0]',
                expected: '1',
                notes: 'currently returns 0 — must not ship as supported',
            },
        ],
    },
    {
        name: 'Series',
        category: 'calculus',
        status: 'partial',
        effect: 'pure',
        notes: 'Exp series works with machine 0.5 coeff; not SeriesData object',
        cases: [
            {
                id: 'series.exp',
                kind: 'eval',
                input: 'Series[Exp[x], {x, 0, 2}]',
                expected: '1 + x + 0.5*x^2',
            },
        ],
    },
    {
        name: 'Solve',
        category: 'solve',
        status: 'planned',
        effect: 'pure',
        notes: 'must lower to Athena SolveGoal; currently unevaluated Application',
        cases: [
            {
                id: 'solve.quad',
                kind: 'gap',
                input: 'Solve[x^2 == 1, x]',
                expected: '{{x -> -1}, {x -> 1}}',
            },
        ],
    },
    {
        name: 'NSolve',
        category: 'solve',
        status: 'planned',
        effect: 'pure',
        cases: [{ id: 'nsolve.quad', kind: 'gap', input: 'NSolve[x^2 == 1, x]', expected: '{{x -> -1.}, {x -> 1.}}' }],
    },
    {
        name: 'Reduce',
        category: 'solve',
        status: 'planned',
        effect: 'pure',
        cases: [{ id: 'reduce.basic', kind: 'gap', input: 'Reduce[x^2 > 0, x]', expected: 'x < 0 || x > 0' }],
    },
    {
        name: 'FindRoot',
        category: 'solve',
        status: 'planned',
        effect: 'pure',
        cases: [{ id: 'findroot.basic', kind: 'gap', input: 'FindRoot[x^2 - 2, {x, 1}]', expected: '{x -> 1.41421}' }],
    },
    {
        name: 'DSolve',
        category: 'solve',
        status: 'planned',
        effect: 'pure',
        cases: [
            {
                id: 'dsolve.basic',
                kind: 'gap',
                input: "DSolve[y'[x] == y[x], y[x], x]",
                expected: '{{y[x] -> E^x C[1]}}',
            },
        ],
    },
    {
        name: 'LinearSolve',
        category: 'linear_algebra',
        status: 'planned',
        effect: 'pure',
        cases: [
            {
                id: 'linearsolve.2x2',
                kind: 'gap',
                input: 'LinearSolve[{{1, 2}, {3, 4}}, {5, 6}]',
                expected: '{-4, 9/2}',
            },
        ],
    },
    {
        name: 'Det',
        category: 'linear_algebra',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'det.2x2', kind: 'gap', input: 'Det[{{1, 2}, {3, 4}}]', expected: '-2' }],
    },
    {
        name: 'Inverse',
        category: 'linear_algebra',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'inverse.eye', kind: 'gap', input: 'Inverse[{{1, 0}, {0, 1}}]', expected: '{{1, 0}, {0, 1}}' }],
    },
    {
        name: 'Transpose',
        category: 'linear_algebra',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'transpose.2x2', kind: 'gap', input: 'Transpose[{{1, 2}, {3, 4}}]', expected: '{{1, 3}, {2, 4}}' }],
    },
    {
        name: 'Dot',
        category: 'linear_algebra',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'dot.mv', kind: 'gap', input: 'Dot[{{1, 2}, {3, 4}}, {1, 1}]', expected: '{3, 7}' }],
    },
    {
        name: 'RowReduce',
        category: 'linear_algebra',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'rowreduce.basic', kind: 'gap', input: 'RowReduce[{{1, 2}, {3, 4}}]', expected: '{{1, 0}, {0, 1}}' }],
    },
    {
        name: 'Table',
        category: 'list',
        status: 'unsupported',
        effect: 'pure',
        notes: 'SILENT WRONG: Table[i,{i,3}] collapses to {i, 3}',
        cases: [
            {
                id: 'table.basic',
                kind: 'gap',
                input: 'Table[i, {i, 3}]',
                expected: '{1, 2, 3}',
                notes: 'currently {i, 3}',
            },
        ],
    },
    {
        name: 'Sum',
        category: 'list',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'sum.basic', kind: 'gap', input: 'Sum[i, {i, 1, 10}]', expected: '55' }],
    },
    {
        name: 'Product',
        category: 'list',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'product.basic', kind: 'gap', input: 'Product[i, {i, 1, 5}]', expected: '120' }],
    },
    {
        name: 'Length',
        category: 'list',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'length.3', kind: 'gap', input: 'Length[{1, 2, 3}]', expected: '3' }],
    },
    {
        name: 'First',
        category: 'list',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'first.ab', kind: 'gap', input: 'First[{a, b}]', expected: 'a' }],
    },
    {
        name: 'Join',
        category: 'list',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'join.basic', kind: 'gap', input: 'Join[{1}, {2}]', expected: '{1, 2}' }],
    },
    {
        name: 'Flatten',
        category: 'list',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'flatten.basic', kind: 'gap', input: 'Flatten[{{1, 2}, {3}}]', expected: '{1, 2, 3}' }],
    },
    {
        name: 'Apply',
        category: 'list',
        status: 'partial',
        effect: 'pure',
        notes: 'SILENT WRONG: Apply[Plus,{1,2,3}] returns {1,2,3} not 6',
        cases: [
            {
                id: 'apply.plus',
                kind: 'gap',
                input: 'Apply[Plus, {1, 2, 3}]',
                expected: '6',
                notes: 'currently returns the list unchanged',
            },
        ],
    },
    {
        name: 'Nest',
        category: 'function',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'nest.inc', kind: 'gap', input: 'Nest[# + 1 &, 0, 3]', expected: '3' }],
    },
    {
        name: 'Fold',
        category: 'function',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'fold.plus', kind: 'gap', input: 'Fold[Plus, 0, {1, 2, 3}]', expected: '6' }],
    },
    {
        name: 'Module',
        category: 'session',
        status: 'unsupported',
        effect: 'stateful',
        notes: 'SILENT WRONG: Module[{x=1},x+1] → 1+x without binding',
        cases: [
            {
                id: 'module.bind',
                kind: 'gap',
                input: 'Module[{x = 1}, x + 1]',
                expected: '2',
                notes: 'currently 1 + x',
            },
        ],
    },
    {
        name: 'With',
        category: 'session',
        status: 'unsupported',
        effect: 'pure',
        notes: 'same binding failure as Module',
        cases: [{ id: 'with.bind', kind: 'gap', input: 'With[{x = 1}, x + 1]', expected: '2' }],
    },
    {
        name: 'Block',
        category: 'session',
        status: 'unsupported',
        effect: 'stateful',
        cases: [{ id: 'block.bind', kind: 'gap', input: 'Block[{x = 1}, x + 1]', expected: '2' }],
    },
    {
        name: 'Blank',
        category: 'pattern',
        status: 'partial',
        effect: 'pure',
        notes: 'Blank/_ stripped or broken: MatchQ[1,_Integer] → MatchQ[1, Integer]; Cases wrong',
        cases: [
            {
                id: 'blank.matchq',
                kind: 'gap',
                input: 'MatchQ[1, _Integer]',
                expected: 'True',
                notes: 'pattern object must stay typed Blank',
            },
        ],
    },
    {
        name: 'N',
        category: 'numeric',
        status: 'unsupported',
        effect: 'pure',
        cases: [
            { id: 'n.pi', kind: 'gap', input: 'N[Pi]', expected: '3.14159' },
            { id: 'n.prec', kind: 'gap', input: 'N[1/3, 20]', expected: '0.33333333333333333333' },
        ],
    },
    {
        name: 'GCD',
        category: 'number_theory',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'gcd.basic', kind: 'gap', input: 'GCD[12, 18]', expected: '6' }],
    },
    {
        name: 'Mod',
        category: 'number_theory',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'mod.basic', kind: 'gap', input: 'Mod[10, 3]', expected: '1' }],
    },
    {
        name: 'PrimeQ',
        category: 'number_theory',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'primeq.7', kind: 'gap', input: 'PrimeQ[7]', expected: 'True' }],
    },
    {
        name: 'Expand',
        category: 'algebra',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'expand.bin', kind: 'gap', input: 'Expand[(x + 1)^2]', expected: '1 + 2*x + x^2' }],
    },
    {
        name: 'Factor',
        category: 'algebra',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'factor.diff', kind: 'gap', input: 'Factor[x^2 - 1]', expected: '(-1 + x)*(1 + x)' }],
    },
    {
        name: 'Max',
        category: 'arithmetic',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'max.3', kind: 'gap', input: 'Max[1, 3, 2]', expected: '3' }],
    },
    {
        name: 'Floor',
        category: 'arithmetic',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'floor.2_7', kind: 'gap', input: 'Floor[2.7]', expected: '2' }],
    },
    {
        name: 'Pi',
        category: 'constant',
        status: 'partial',
        effect: 'pure',
        notes: 'symbol retained; no numeric value without N',
        cases: [{ id: 'pi.symbol', kind: 'eval', input: 'Pi', expected: 'Pi' }],
    },
    {
        name: 'I',
        category: 'constant',
        status: 'partial',
        effect: 'pure',
        notes: 'symbol only; Re/Im/Conjugate unevaluated',
        cases: [{ id: 'i.symbol', kind: 'eval', input: 'I', expected: 'I' }],
    },
    {
        name: 'Import',
        category: 'io',
        status: 'unsupported',
        effect: 'effectful',
        notes: 'SILENT WRONG: Import[\"x.csv\"] returns \"x.csv\" string',
        cases: [
            {
                id: 'import.strip',
                kind: 'gap',
                input: 'Import["x.csv"]',
                expected: 'UnsupportedOperation',
                notes: 'must not strip to filename',
            },
        ],
    },
    {
        name: 'Export',
        category: 'io',
        status: 'unsupported',
        effect: 'effectful',
        notes: 'SILENT WRONG: Export[\"x.csv\",1] returns 1',
        cases: [
            {
                id: 'export.strip',
                kind: 'gap',
                input: 'Export["x.csv", 1]',
                expected: 'UnsupportedOperation',
            },
        ],
    },
    {
        name: 'StringLength',
        category: 'string',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'strlen.ab', kind: 'gap', input: 'StringLength["ab"]', expected: '2' }],
    },
    {
        name: 'ListPlot',
        category: 'plot',
        status: 'unsupported',
        effect: 'effectful',
        cases: [{ id: 'listplot.basic', kind: 'gap', input: 'ListPlot[{{1, 1}, {2, 4}}]', expected: '<svg' }],
    },
    {
        name: 'Plot3D',
        category: 'plot',
        status: 'unsupported',
        effect: 'effectful',
        notes: 'juxtaposition x y may parse as sequence; no 3-D path',
        cases: [{ id: 'plot3d.basic', kind: 'gap', input: 'Plot3D[x*y, {x, 0, 1}, {y, 0, 1}]', expected: '<svg' }],
    },
    {
        name: 'Plot',
        category: 'plot',
        status: 'partial',
        effect: 'effectful',
        notes: 'SVG→PNG visual: curve+L-axes readable; missing tick labels, no Frame, not commercial MMA axes-at-origin. Negative domain {x,-1,1} extract fails',
        cases: [
            {
                id: 'plot.square',
                kind: 'plot',
                input: 'Plot[x^2, {x, 0, 1}]',
                expected: '<svg',
            },
            {
                id: 'plot.sin',
                kind: 'plot',
                input: 'Plot[Sin[x], {x, 0, 6}]',
                expected: '<svg',
            },
            {
                id: 'plot.neg_domain',
                kind: 'gap',
                input: 'Plot[x^2, {x, -1, 1}]',
                expected: '<svg',
                notes: 'unary minus in iterator breaks plot extract',
            },
        ],
    },
    {
        name: 'ExactInteger',
        category: 'numeric',
        status: 'supported',
        effect: 'pure',
        cases: [
            {
                id: 'bigint.add',
                kind: 'eval',
                input: '99999999999999999999 + 1',
                expected: '100000000000000000000',
            },
        ],
    },
    {
        name: 'True',
        category: 'constant',
        status: 'unsupported',
        effect: 'pure',
        notes: 'oak empty root on bare True',
        cases: [{ id: 'true.atom', kind: 'gap', input: 'True', expected: 'True' }],
    },
    {
        name: 'False',
        category: 'constant',
        status: 'unsupported',
        effect: 'pure',
        notes: 'oak empty root on bare False',
        cases: [{ id: 'false.atom', kind: 'gap', input: 'False', expected: 'False' }],
    },
    {
        name: 'Null',
        category: 'constant',
        status: 'unsupported',
        effect: 'pure',
        cases: [{ id: 'null.atom', kind: 'gap', input: 'Null', expected: 'Null' }],
    },
    {
        name: 'E',
        category: 'constant',
        status: 'partial',
        effect: 'pure',
        cases: [{ id: 'e.symbol', kind: 'eval', input: 'E', expected: 'E' }],
    },
    {
        name: 'ArithCanonical',
        category: 'arithmetic',
        status: 'supported',
        effect: 'pure',
        notes: 'identity folds x+0 / 1*x / x^0 / like powers',
        cases: [
            { id: 'arith.x_plus_0', kind: 'eval', input: 'x + 0', expected: 'x' },
            { id: 'arith.one_times_x', kind: 'eval', input: '1 * x', expected: 'x' },
            { id: 'arith.x_pow_0', kind: 'eval', input: 'x^0', expected: '1' },
            { id: 'arith.pow_combine', kind: 'eval', input: 'x^2 * x^3', expected: 'x^5' },
        ],
    },
    {
        name: 'Head',
        category: 'meta',
        status: 'unsupported',
        effect: 'pure',
        notes: 'Head evaluates args first: Head[1+2] → Head[3]; Head[{1,2}] unevaluated',
        cases: [
            { id: 'head.list', kind: 'gap', input: 'Head[{1, 2}]', expected: 'List' },
            { id: 'head.plus', kind: 'gap', input: 'Head[a + b]', expected: 'Plus' },
        ],
    },
] as const satisfies readonly FeatureEntry[];
